# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.pagination import AsyncPager, SyncPager
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...errors.unprocessable_entity_error import UnprocessableEntityError
from ...types.api_counted_list_response_workflow_run_list_item import ApiCountedListResponseWorkflowRunListItem
from ...types.api_response_workflow_run_detail_out import ApiResponseWorkflowRunDetailOut
from ...types.api_response_workflow_run_out import ApiResponseWorkflowRunOut
from ...types.http_validation_error import HttpValidationError
from ...types.workflow_run_list_item import WorkflowRunListItem
from .types.list_runs_request_order import ListRunsRequestOrder
from .types.list_runs_request_sort import ListRunsRequestSort
from pydantic import ValidationError


class RawRunsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        workflow_id: str,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[ListRunsRequestSort] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WorkflowRunListItem, ApiCountedListResponseWorkflowRunListItem]:
        """
        List runs for a workflow.

        Tiebreaker is always ``id ASC`` so offset/limit pagination is stable when
        primary sort keys tie. ``status`` accepts comma-separated raw RunStatus
        values; unknown values return 422. ``search`` matches the triggering
        user's display name (full name, falling back to email).

        Parameters
        ----------
        workflow_id : str

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[str]
            Comma-separated raw RunStatus values (e.g. `completed,failed`). Values are case-sensitive lowercase. Multiple values OR-match. Empty tokens (e.g. `a,,b`) and unknown values return 422.

        search : typing.Optional[str]
            Case-insensitive search over triggering user's display name and email.

        sort : typing.Optional[ListRunsRequestSort]
            Sort field: created_at | started_at | completed_at | status.

        order : typing.Optional[ListRunsRequestOrder]
            asc or desc.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WorkflowRunListItem, ApiCountedListResponseWorkflowRunListItem]
            Successful Response
        """
        offset = offset if offset is not None else 0

        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "status": status,
                "search": search,
                "sort": sort,
                "order": order,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ApiCountedListResponseWorkflowRunListItem,
                    parse_obj_as(
                        type_=ApiCountedListResponseWorkflowRunListItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = True
                _get_next = lambda: self.list(
                    workflow_id,
                    offset=offset + len(_items or []),
                    limit=limit,
                    status=status,
                    search=search,
                    sort=sort,
                    order=order,
                    workspace_id=workspace_id,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def start(
        self,
        workflow_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseWorkflowRunOut]:
        """
        Start a workflow run.

        Parameters
        ----------
        workflow_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseWorkflowRunDetailOut]:
        """
        Fetch a workflow run by id.

        Includes `definition_snapshot` — the graph/execution config captured
        when the run started, returned raw (no config migrations applied) so
        it reflects the workflow exactly as it existed for this run.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseWorkflowRunDetailOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunDetailOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunDetailOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def status(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseWorkflowRunOut]:
        """
        Lightweight run status for polling.

        Returns only the volatile run state (status, step counts, timestamps,
        usage_summary, error, has_export) — no graph snapshot. Use this for
        progress polling; call `GET /runs/{run_id}` once to load the immutable
        definition snapshot.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}/status",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseWorkflowRunOut]:
        """
        Cancel a running workflow run.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}/cancel",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRunsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        workflow_id: str,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[ListRunsRequestSort] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WorkflowRunListItem, ApiCountedListResponseWorkflowRunListItem]:
        """
        List runs for a workflow.

        Tiebreaker is always ``id ASC`` so offset/limit pagination is stable when
        primary sort keys tie. ``status`` accepts comma-separated raw RunStatus
        values; unknown values return 422. ``search`` matches the triggering
        user's display name (full name, falling back to email).

        Parameters
        ----------
        workflow_id : str

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[str]
            Comma-separated raw RunStatus values (e.g. `completed,failed`). Values are case-sensitive lowercase. Multiple values OR-match. Empty tokens (e.g. `a,,b`) and unknown values return 422.

        search : typing.Optional[str]
            Case-insensitive search over triggering user's display name and email.

        sort : typing.Optional[ListRunsRequestSort]
            Sort field: created_at | started_at | completed_at | status.

        order : typing.Optional[ListRunsRequestOrder]
            asc or desc.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WorkflowRunListItem, ApiCountedListResponseWorkflowRunListItem]
            Successful Response
        """
        offset = offset if offset is not None else 0

        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "status": status,
                "search": search,
                "sort": sort,
                "order": order,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ApiCountedListResponseWorkflowRunListItem,
                    parse_obj_as(
                        type_=ApiCountedListResponseWorkflowRunListItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = True

                async def _get_next():
                    return await self.list(
                        workflow_id,
                        offset=offset + len(_items or []),
                        limit=limit,
                        status=status,
                        search=search,
                        sort=sort,
                        order=order,
                        workspace_id=workspace_id,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def start(
        self,
        workflow_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseWorkflowRunOut]:
        """
        Start a workflow run.

        Parameters
        ----------
        workflow_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseWorkflowRunDetailOut]:
        """
        Fetch a workflow run by id.

        Includes `definition_snapshot` — the graph/execution config captured
        when the run started, returned raw (no config migrations applied) so
        it reflects the workflow exactly as it existed for this run.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseWorkflowRunDetailOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunDetailOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunDetailOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def status(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseWorkflowRunOut]:
        """
        Lightweight run status for polling.

        Returns only the volatile run state (status, step counts, timestamps,
        usage_summary, error, has_export) — no graph snapshot. Use this for
        progress polling; call `GET /runs/{run_id}` once to load the immutable
        definition snapshot.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}/status",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel(
        self,
        workflow_id: str,
        run_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseWorkflowRunOut]:
        """
        Cancel a running workflow run.

        Parameters
        ----------
        workflow_id : str

        run_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseWorkflowRunOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/workflows/{encode_path_param(workflow_id)}/runs/{encode_path_param(run_id)}/cancel",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseWorkflowRunOut,
                    parse_obj_as(
                        type_=ApiResponseWorkflowRunOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
