# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_counted_list_response_voice_out import ApiCountedListResponseVoiceOut
from ..types.api_list_response_voice_similar_out import ApiListResponseVoiceSimilarOut
from ..types.api_response_dict import ApiResponseDict
from ..types.api_response_voice_facets_out import ApiResponseVoiceFacetsOut
from ..types.api_response_voice_out import ApiResponseVoiceOut
from ..types.voice_accent import VoiceAccent
from ..types.voice_age import VoiceAge
from ..types.voice_category import VoiceCategory
from ..types.voice_gender import VoiceGender
from .raw_client import AsyncRawVoicesClient, RawVoicesClient
from .types.get_voice_facets_api_v1voices_facets_get_request_source_item import (
    GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem,
)
from .types.list_voices_request_language_item import ListVoicesRequestLanguageItem
from .types.list_voices_request_order_item import ListVoicesRequestOrderItem
from .types.list_voices_request_sort_item import ListVoicesRequestSortItem
from .types.list_voices_request_source_item import ListVoicesRequestSourceItem


class VoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVoicesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[typing.Sequence[ListVoicesRequestSortItem]] = None,
        order: typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiCountedListResponseVoiceOut:
        """
        List TTS voices available to the current workspace.

        Every filter accepts repeat-key OR semantics:
        `?gender=female&gender=neutral&category=narration&source=platform&source=workspace`.
        Filters combine across fields with AND; within a field, values OR.

        `language` matches a voice when any of its declared locales matches any
        requested value. Platform voices with no declared locales (catalog gaps)
        are treated as general-use and match every language filter. User-uploaded
        / cloned voices with no declared locales are excluded — that state means
        "language unknown" pending the clone flow's language detection.

        Multi-sort: `sort` and `order` are parallel lists. `?sort=uses_count&sort=name&order=desc&order=asc`
        orders primarily by uses_count DESC, secondarily by name ASC. When `order`
        is shorter than `sort`, missing entries default per-field:
        `name=asc, created_at=desc, uses_count=desc`. When `sort` is omitted, list
        defaults to newest-first (or most-recently-favorited-first if
        `favorites_only=true`). Every sort path appends `Voice.id ASC` as a
        deterministic tiebreaker for pagination stability.

        Parameters
        ----------
        offset : typing.Optional[int]
            Number of results to skip for pagination.

        limit : typing.Optional[int]
            Maximum number of results to return (1–100).

        favorites_only : typing.Optional[bool]
            When true, return only voices in the workspace's favorites list.

        source : typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]]
            Repeat for OR across scopes: `platform` for system-provided voices, `workspace` for workspace-owned voices.

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]
            Full-text search against voice name, description, and tags.

        sort : typing.Optional[typing.Sequence[ListVoicesRequestSortItem]]
            Repeat for multi-sort. Pairs with `order` index-wise.

        order : typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]]
            Parallel to sort[]; shorter is padded with per-field defaults.

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiCountedListResponseVoiceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.list()
        """
        _response = self._raw_client.list(
            offset=offset,
            limit=limit,
            favorites_only=favorites_only,
            source=source,
            gender=gender,
            age=age,
            category=category,
            accent=accent,
            search=search,
            sort=sort,
            order=order,
            provider=provider,
            model=model,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    def get_voice_facets(
        self,
        *,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceFacetsOut:
        """
        Filter-bar options (chips) for the voice browser, one list per dimension.

        Returns `providers`, `models`, `languages` (data-driven) plus `genders`,
        `ages`, `categories`, `accents` (fixed enums) as `VoiceFacetItem[]` so the FE
        builds the whole filter bar — with per-chip count badges — in a single request
        instead of hardcoding option lists (mirrors `GET /dictionary/languages`). Each
        item is `{value, label, count}`: `value` is passed straight back to
        `GET /voices`; `label` is the display name for providers/models and `null`
        elsewhere (the FE owns language + enum labels); `count` is the number of
        matching voices. For `languages`/`models`, `count` counts only voices that
        explicitly declare the value — "general-use" platform voices (no declared
        locales/models) that `GET /voices` matches against every language/model filter
        are not counted, so a chip's count can be lower than the `GET /voices` result.

        Accepts the SAME filters as `GET /voices` (tab scope `source`/`favorites_only`,
        plus `provider`/`model`/`language`/`gender`/`age`/`category`/`accent`/`search`).
        `count` is context-aware (faceted search): each dimension's counts apply every
        OTHER active filter but exclude that dimension's own selection — e.g. with
        `provider=elevenlabs` the language counts are scoped to ElevenLabs, while the
        provider chips still show every provider so the caller can switch.

        Count-0 policy: data-driven dimensions omit count-0 values (only present ones,
        each a valid `GET /voices` filter — providers/models restricted to the enabled
        catalog, languages to the supported-locale allowlist, so a chip never 422s).
        Enum dimensions always return the full enum in natural order, count-0 included,
        for the FE to grey out.

        Parameters
        ----------
        favorites_only : typing.Optional[bool]
            Favorites tab scope

        source : typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]]
            Tab scope — repeat for OR, same values as GET /voices (e.g. platform, workspace)

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceFacetsOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.get_voice_facets()
        """
        _response = self._raw_client.get_voice_facets(
            favorites_only=favorites_only,
            source=source,
            gender=gender,
            age=age,
            category=category,
            accent=accent,
            search=search,
            provider=provider,
            model=model,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceOut:
        """
        Fetch a single voice by its ID.

        Returns both platform (system-wide) voices and voices that belong to the
        caller's workspace. Returns 404 when the voice does not exist or is not
        accessible to the caller's workspace. The `sample_url` field is a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.get(
            voice_id="voice_id",
        )
        """
        _response = self._raw_client.get(voice_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data

    def similar(
        self,
        voice_id: str,
        *,
        limit: typing.Optional[int] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseVoiceSimilarOut:
        """
        Return voices acoustically similar to a reference voice.

        Results are ranked by semantic similarity score (descending) and include the
        reference voice's workspace voices and all platform voices. Each result
        includes a `similarity_score` between 0 and 1. Optionally filter by one or
        more `language` BCP-47 codes (repeat the parameter for OR semantics); up to
        16 language values are accepted. Returns 503 when the reference voice has no
        embedding yet — retry after the indicated `Retry-After` interval. Prefer this
        endpoint over `GET /voices` with manual filtering when building a
        "voices like this" recommendation UI.

        Parameters
        ----------
        voice_id : str

        limit : typing.Optional[int]
            Number of similar voices to return (1–50).

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseVoiceSimilarOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.similar(
            voice_id="voice_id",
        )
        """
        _response = self._raw_client.similar(
            voice_id, limit=limit, language=language, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def favorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceOut:
        """
        Add a voice to the current workspace's favorites.

        Favorites are workspace-scoped, not per-user: all members of the workspace
        see the same favorited set. Idempotent — favoriting a voice that is already
        favorited succeeds without error. Returns the voice with `is_favorite=true`.
        Requires the caller to have at least editor role in the workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.favorite_voice(
            voice_id="voice_id",
        )
        """
        _response = self._raw_client.favorite_voice(
            voice_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def unfavorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Remove a voice from the current workspace's favorites.

        Idempotent — removing a voice that is not currently favorited succeeds
        without error. Requires the caller to have at least editor role in the
        workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.voices.unfavorite_voice(
            voice_id="voice_id",
        )
        """
        _response = self._raw_client.unfavorite_voice(
            voice_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncVoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVoicesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[typing.Sequence[ListVoicesRequestSortItem]] = None,
        order: typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiCountedListResponseVoiceOut:
        """
        List TTS voices available to the current workspace.

        Every filter accepts repeat-key OR semantics:
        `?gender=female&gender=neutral&category=narration&source=platform&source=workspace`.
        Filters combine across fields with AND; within a field, values OR.

        `language` matches a voice when any of its declared locales matches any
        requested value. Platform voices with no declared locales (catalog gaps)
        are treated as general-use and match every language filter. User-uploaded
        / cloned voices with no declared locales are excluded — that state means
        "language unknown" pending the clone flow's language detection.

        Multi-sort: `sort` and `order` are parallel lists. `?sort=uses_count&sort=name&order=desc&order=asc`
        orders primarily by uses_count DESC, secondarily by name ASC. When `order`
        is shorter than `sort`, missing entries default per-field:
        `name=asc, created_at=desc, uses_count=desc`. When `sort` is omitted, list
        defaults to newest-first (or most-recently-favorited-first if
        `favorites_only=true`). Every sort path appends `Voice.id ASC` as a
        deterministic tiebreaker for pagination stability.

        Parameters
        ----------
        offset : typing.Optional[int]
            Number of results to skip for pagination.

        limit : typing.Optional[int]
            Maximum number of results to return (1–100).

        favorites_only : typing.Optional[bool]
            When true, return only voices in the workspace's favorites list.

        source : typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]]
            Repeat for OR across scopes: `platform` for system-provided voices, `workspace` for workspace-owned voices.

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]
            Full-text search against voice name, description, and tags.

        sort : typing.Optional[typing.Sequence[ListVoicesRequestSortItem]]
            Repeat for multi-sort. Pairs with `order` index-wise.

        order : typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]]
            Parallel to sort[]; shorter is padded with per-field defaults.

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiCountedListResponseVoiceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            offset=offset,
            limit=limit,
            favorites_only=favorites_only,
            source=source,
            gender=gender,
            age=age,
            category=category,
            accent=accent,
            search=search,
            sort=sort,
            order=order,
            provider=provider,
            model=model,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    async def get_voice_facets(
        self,
        *,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceFacetsOut:
        """
        Filter-bar options (chips) for the voice browser, one list per dimension.

        Returns `providers`, `models`, `languages` (data-driven) plus `genders`,
        `ages`, `categories`, `accents` (fixed enums) as `VoiceFacetItem[]` so the FE
        builds the whole filter bar — with per-chip count badges — in a single request
        instead of hardcoding option lists (mirrors `GET /dictionary/languages`). Each
        item is `{value, label, count}`: `value` is passed straight back to
        `GET /voices`; `label` is the display name for providers/models and `null`
        elsewhere (the FE owns language + enum labels); `count` is the number of
        matching voices. For `languages`/`models`, `count` counts only voices that
        explicitly declare the value — "general-use" platform voices (no declared
        locales/models) that `GET /voices` matches against every language/model filter
        are not counted, so a chip's count can be lower than the `GET /voices` result.

        Accepts the SAME filters as `GET /voices` (tab scope `source`/`favorites_only`,
        plus `provider`/`model`/`language`/`gender`/`age`/`category`/`accent`/`search`).
        `count` is context-aware (faceted search): each dimension's counts apply every
        OTHER active filter but exclude that dimension's own selection — e.g. with
        `provider=elevenlabs` the language counts are scoped to ElevenLabs, while the
        provider chips still show every provider so the caller can switch.

        Count-0 policy: data-driven dimensions omit count-0 values (only present ones,
        each a valid `GET /voices` filter — providers/models restricted to the enabled
        catalog, languages to the supported-locale allowlist, so a chip never 422s).
        Enum dimensions always return the full enum in natural order, count-0 included,
        for the FE to grey out.

        Parameters
        ----------
        favorites_only : typing.Optional[bool]
            Favorites tab scope

        source : typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]]
            Tab scope — repeat for OR, same values as GET /voices (e.g. platform, workspace)

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceFacetsOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.get_voice_facets()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_voice_facets(
            favorites_only=favorites_only,
            source=source,
            gender=gender,
            age=age,
            category=category,
            accent=accent,
            search=search,
            provider=provider,
            model=model,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceOut:
        """
        Fetch a single voice by its ID.

        Returns both platform (system-wide) voices and voices that belong to the
        caller's workspace. Returns 404 when the voice does not exist or is not
        accessible to the caller's workspace. The `sample_url` field is a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.get(
                voice_id="voice_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(voice_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data

    async def similar(
        self,
        voice_id: str,
        *,
        limit: typing.Optional[int] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseVoiceSimilarOut:
        """
        Return voices acoustically similar to a reference voice.

        Results are ranked by semantic similarity score (descending) and include the
        reference voice's workspace voices and all platform voices. Each result
        includes a `similarity_score` between 0 and 1. Optionally filter by one or
        more `language` BCP-47 codes (repeat the parameter for OR semantics); up to
        16 language values are accepted. Returns 503 when the reference voice has no
        embedding yet — retry after the indicated `Retry-After` interval. Prefer this
        endpoint over `GET /voices` with manual filtering when building a
        "voices like this" recommendation UI.

        Parameters
        ----------
        voice_id : str

        limit : typing.Optional[int]
            Number of similar voices to return (1–50).

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseVoiceSimilarOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.similar(
                voice_id="voice_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.similar(
            voice_id, limit=limit, language=language, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def favorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseVoiceOut:
        """
        Add a voice to the current workspace's favorites.

        Favorites are workspace-scoped, not per-user: all members of the workspace
        see the same favorited set. Idempotent — favoriting a voice that is already
        favorited succeeds without error. Returns the voice with `is_favorite=true`.
        Requires the caller to have at least editor role in the workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseVoiceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.favorite_voice(
                voice_id="voice_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.favorite_voice(
            voice_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def unfavorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Remove a voice from the current workspace's favorites.

        Idempotent — removing a voice that is not currently favorited succeeds
        without error. Requires the caller to have at least editor role in the
        workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voices.unfavorite_voice(
                voice_id="voice_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unfavorite_voice(
            voice_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
