# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.api_counted_list_response_voice_out import ApiCountedListResponseVoiceOut
from ..types.api_list_response_voice_similar_out import ApiListResponseVoiceSimilarOut
from ..types.api_response_dict import ApiResponseDict
from ..types.api_response_voice_facets_out import ApiResponseVoiceFacetsOut
from ..types.api_response_voice_out import ApiResponseVoiceOut
from ..types.api_response_voice_preview_out import ApiResponseVoicePreviewOut
from ..types.voice_accent import VoiceAccent
from ..types.voice_age import VoiceAge
from ..types.voice_category import VoiceCategory
from ..types.voice_gender import VoiceGender
from .types.get_voice_facets_api_v1voices_facets_get_request_source_item import (
    GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem,
)
from .types.list_voices_request_language_item import ListVoicesRequestLanguageItem
from .types.list_voices_request_order_item import ListVoicesRequestOrderItem
from .types.list_voices_request_sort_item import ListVoicesRequestSortItem
from .types.list_voices_request_source_item import ListVoicesRequestSourceItem
from .types.preview_voices_request_language import PreviewVoicesRequestLanguage
from pydantic import ValidationError


class RawVoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[typing.Sequence[ListVoicesRequestSortItem]] = None,
        order: typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]] = None,
        buildable: typing.Optional[bool] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiCountedListResponseVoiceOut]:
        """
        List TTS voices available to the current workspace.

        Every filter accepts repeat-key OR semantics:
        `?gender=female&gender=neutral&category=narration&source=platform&source=workspace`.
        Filters combine across fields with AND; within a field, values OR.

        Hybrid search: when `search` is a non-empty string, semantic search is enabled
        for the deployment (`VOICE_SEMANTIC_SEARCH_ENABLED`), and the text embedder is
        available, `search` runs a hybrid of SEMANTIC relevance — meaning, not keywords, so
        "cheerful" also surfaces "bright/upbeat" voices, over the platform voices that carry a
        profile embedding — AND a keyword arm that matches the voice NAME (plus descriptor/tags),
        which also surfaces voices with no embedding and workspace-owned voices in scope, so a
        voice literally named by the query is found. Both arms honor the same filters and are
        fused into one ranking. In that mode `sort`/`order` are IGNORED (relevance order wins).
        If semantic search is disabled, the embedder is
        unavailable, or the embed call fails, `search` transparently falls back to the
        lexical name/tag/descriptor match described below — the response shape
        (`ApiCountedListResponse[VoiceOut]`) is identical either way.

        `language` matches a voice when any of its declared locales matches any
        requested value. A voice with no declared locales matches NO `language`
        filter — it must positively declare a locale to surface under it. This holds
        for platform and user-uploaded voices alike: an unclassified platform voice
        (catalog gap) is not treated as general-use, and a user-uploaded/cloned voice
        with no locale stays "language unknown" pending clone-flow detection.

        Passing `language` also fills `language_sample_url` on every row that has a clip
        in it — the same audio `GET /voices/{voice_id}/preview?language=` serves, so a
        caller auditioning a shortlist can play the locale-correct take straight from the
        list instead of a request per voice. `language_sample_locale` reports the region
        actually served. Both are null without the filter; `sample_url` is unaffected and
        still does not follow it.

        Platform voices are restricted to the officially supported locales: a platform
        voice that declares no official locale is not returned, and the locale arrays on
        the voices that are returned (`supported_languages`,
        `model_capabilities[].supported_languages`, `preview_locales`) list only official
        locales. A bare family code counts as official when the family is supported
        (`ko` qualifies because `ko-kr` is), matching the `language` filter above. Voices
        your workspace owns — imported, recorded, or uploaded — are exempt from both the
        exclusion and the narrowing: they routinely carry no declared locale at all, and
        hiding them would remove a customer's own voices from their own list.

        `buildable=true` narrows platform voices to the ones that can actually be
        SYNTHESIZED for `language`: the voice must have a measured `(provider, model, locale)`
        pair that clears the quality floors used by automatic voice selection, on a provider
        and model that are enabled, currently routable for synthesis, and carry a billable
        rate (or one your workspace holds a valid BYOK key for), and the voice must itself be
        able to speak that locale on that model.
        Without it the list is a raw catalogue browse that can return a voice a run would
        refuse — the same voice the assistant's own cards never offer. It **requires**
        `language` (422 otherwise): the measurements are per-locale, so "buildable" has no
        meaning until you say buildable for what. Repeating `language` asks whether the voice
        is buildable for AT LEAST ONE of them, and each locale is judged whole: a voice
        measured only for `en-us` is not returned for `?language=en-gb&language=en-us` unless
        it can speak `en-us` itself. Voices your workspace owns are returned
        either way — nothing measures a customer's own voice, so there is no pair to clear.
        `pagination.total` follows the same narrowing, so paging cannot walk past the gate.
        Transient provider health is deliberately NOT part of this filter; a vendor whose
        circuit breaker is open still lists. A vendor whose credentials cannot be resolved at
        all is a different case and IS excluded — that failure is not transient.

        `GET /voices/facets` does NOT take this parameter, so its chip counts are ungated and
        a chip can over-count relative to a `buildable=true` page. Gating them needs the
        LANGUAGE dimension evaluated per candidate locale — a language chip self-excludes the
        `language` filter this gate is defined against, so reusing the request's own locales
        would count every chip against the locale already selected — and that is a separate
        change from this one.

        Multi-sort: `sort` and `order` are parallel lists. `?sort=uses_count&sort=name&order=desc&order=asc`
        orders primarily by uses_count DESC, secondarily by name ASC. When `order`
        is shorter than `sort`, missing entries default per-field:
        `name=asc, created_at=desc, uses_count=desc`. When `sort` is omitted, list
        defaults to newest-first (or most-recently-favorited-first if
        `favorites_only=true`). Every sort path appends `Voice.id ASC` as a
        deterministic tiebreaker for pagination stability.

        Parameters
        ----------
        offset : typing.Optional[int]
            Number of results to skip for pagination.

        limit : typing.Optional[int]
            Maximum number of results to return (1–100).

        favorites_only : typing.Optional[bool]
            When true, return only voices in the workspace's favorites list.

        source : typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]]
            Repeat for OR across scopes: `platform` for system-provided voices, `workspace` for workspace-owned voices.

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]
            Searches name, tags, and the voice's summary-derived descriptor text (closely tracks the served description; summary beyond 200 chars is not searched).

        sort : typing.Optional[typing.Sequence[ListVoicesRequestSortItem]]
            Repeat for multi-sort. Pairs with `order` index-wise.

        order : typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]]
            Parallel to sort[]; shorter is padded with per-field defaults.

        buildable : typing.Optional[bool]
            Return only voices that can actually be synthesized for `language`: the measured quality floors, a provider/model that is enabled AND currently routable, and a billable rate (or your own BYOK key). Requires `language`; each repeated value is judged on its own. Voices your workspace owns are always returned.

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiCountedListResponseVoiceOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/voices",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "favorites_only": favorites_only,
                "source": source,
                "gender": gender,
                "age": age,
                "category": category,
                "accent": accent,
                "search": search,
                "sort": sort,
                "order": order,
                "buildable": buildable,
                "provider": provider,
                "model": model,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiCountedListResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiCountedListResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_voice_facets(
        self,
        *,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseVoiceFacetsOut]:
        """
        Filter-bar options (chips) for the voice browser, one list per dimension.

        Returns `providers`, `models`, `languages` (data-driven) plus `genders`,
        `ages`, `categories`, `accents` (fixed enums) as `VoiceFacetItem[]` so the FE
        builds the whole filter bar — with per-chip count badges — in a single request
        instead of hardcoding option lists (mirrors `GET /dictionary/languages`). Each
        item is `{value, label, count}`: `value` is passed straight back to
        `GET /voices`; `label` is the display name for providers/models and `null`
        elsewhere (the FE owns language + enum labels); `count` is the number of
        matching voices. A language surfaces as one chip keyed by its canonical
        allowlist locale: every declared locale is folded onto the locale the
        `GET /voices` filter would match it against (bare `ko` and regioned `ko-kr`
        both count under `ko-kr`), so variants never split into duplicate chips for
        the identical filter. Model counts include only voices that explicitly declare
        the model. Language counts include voices that declare the exact regional locale
        plus voices that declare its bare family (`en` contributes to every supported
        `en-*` locale). A voice with no declared `supported_models` is "general use" —
        `GET /voices` matches it against every model filter but no `models` chip counts
        it, so a model chip's count can be lower than the `GET /voices?model=` result.
        Languages have no such gap: no-locale voices are excluded from both the language
        chips and `GET /voices?language=`, so language chip counts match the row counts.

        Accepts the SAME filters as `GET /voices` (tab scope `source`/`favorites_only`,
        plus `provider`/`model`/`language`/`gender`/`age`/`category`/`accent`/`search`).
        `count` is context-aware (faceted search): each dimension's counts apply every
        OTHER active filter but exclude that dimension's own selection — e.g. with
        `provider=elevenlabs` the language counts are scoped to ElevenLabs, while the
        provider chips still show every provider so the caller can switch.

        `search` follows the SAME two modes as `GET /voices` (see `_semantic_search_active`).
        In SEMANTIC mode (flag on, embedder available, platform in scope) the chips are
        counted over the population the semantic list can return — every active filter, plus
        "carries a description embedding OR is in the current ranked set" (the ANN only ranks
        embedded voices; the keyword arm contributes the rest) — so the chips describe the
        voices the list actually shows and never collapse to "No matches" on a query that has
        no literal name/tag hit. Per-dimension self-exclusion applies in full, exactly as in
        lexical mode. Counts are clamped to `VOICE_SEARCH_MAX_RANKED`, because the semantic
        list's `pagination.total` is that same capped ranked-set size — so a chip's `count` is
        the number of rows `GET /voices` returns once that value is selected. Two bounded
        exceptions: a voice reachable only through the keyword arm is counted only under the
        value already selected (the ranked set is computed under the current filters), and
        ANN recall can return fewer rows than the chip promises. In the LEXICAL
        fallback (flag off / no embedder / non-platform source / embed fault) `search` is the
        `name`/`descriptor`/`tags` ILIKE and counts are exact (no cap), exactly as before.

        No `buildable` parameter: unlike `GET /voices` these counts are NOT narrowed to
        synthesizable voices, so against a `buildable=true` page a chip can over-count. The
        language dimension is why — a language chip deliberately self-excludes the `language`
        filter that gate is defined against, so it has to be evaluated per candidate locale
        rather than against the request's own, and the legacy-JSONB half of the language count
        is aggregated in Python with no query to attach it to.

        Chips are drawn from the same population `GET /voices` returns, so the
        official-locale restriction applies here too and no chip can open an empty page.
        For the `model` dimension the restriction is evaluated per capability row rather
        than per voice — a voice whose only official locale sits on a sibling model does
        not count toward this model's chip, because `GET /voices?model=` would not return
        it either.

        Count-0 policy: data-driven dimensions omit count-0 values (only present ones,
        each a valid `GET /voices` filter — providers/models restricted to the enabled
        catalog, languages to the supported-locale allowlist, so a chip never 422s).
        Enum dimensions always return the full enum in natural order, count-0 included,
        for the FE to grey out.

        Parameters
        ----------
        favorites_only : typing.Optional[bool]
            Favorites tab scope

        source : typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]]
            Tab scope — repeat for OR, same values as GET /voices (e.g. platform, workspace)

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseVoiceFacetsOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/voices/facets",
            method="GET",
            params={
                "favorites_only": favorites_only,
                "source": source,
                "gender": gender,
                "age": age,
                "category": category,
                "accent": accent,
                "search": search,
                "provider": provider,
                "model": model,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceFacetsOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceFacetsOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseVoiceOut]:
        """
        Fetch a single voice by its ID.

        Returns both platform (system-wide) voices and voices that belong to the
        caller's workspace. Returns 404 when the voice does not exist, is not
        accessible to the caller's workspace, or is a platform voice from a provider
        that is not available to your account. Voices your workspace owns stay
        readable regardless of provider availability. The `sample_url` field is a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term. This endpoint sets
        `Cache-Control: no-store` because the response bakes in that short-lived
        presigned URL — server-side (Redis) caching still applies underneath.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseVoiceOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def similar(
        self,
        voice_id: str,
        *,
        limit: typing.Optional[int] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiListResponseVoiceSimilarOut]:
        """
        Return voices acoustically similar to a reference voice.

        Results are ranked by semantic similarity score (descending) and include the
        reference voice's workspace voices and all platform voices. Each result
        includes a `similarity_score` between 0 and 1. Optionally filter by one or
        more `language` BCP-47 codes (repeat the parameter for OR semantics); up to
        16 language values are accepted. Results are restricted to officially supported
        locales on the same terms as `GET /voices`; the reference voice itself is not,
        so you can ask for neighbours of a voice that no longer appears in the list.
        Returns 503 when the reference voice has no embedding yet — retry after the
        indicated `Retry-After` interval. Prefer this
        endpoint over `GET /voices` with manual filtering when building a
        "voices like this" recommendation UI.

        Platform voices from providers that are not available to your account are
        rejected as a reference (404) and omitted from the results; voices your
        workspace owns are unaffected. This endpoint sets `Cache-Control: no-store`
        because the response bakes in short-lived presigned sample URLs — server-side
        (Redis) caching still applies underneath for the default `limit`/`language` shape.

        Parameters
        ----------
        voice_id : str

        limit : typing.Optional[int]
            Number of similar voices to return (1–50).

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiListResponseVoiceSimilarOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/similar",
            method="GET",
            params={
                "limit": limit,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseVoiceSimilarOut,
                    parse_obj_as(
                        type_=ApiListResponseVoiceSimilarOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def preview(
        self,
        voice_id: str,
        *,
        language: PreviewVoicesRequestLanguage,
        model: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseVoicePreviewOut]:
        """
        Fetch ready-to-play preview audio for one voice in one language.

        Returns the voice's `name`, the preview's `locale`, the `model` it was
        synthesized with, its stored `content_type`, and a `sample_url` — a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term. Pass `model` to prefer a
        specific TTS model; a preview from another model is still returned when
        that model has none.

        `language` accepts a bare family (`ko`, `en`) as well as an exact locale
        (`ko-kr`, `en-gb`). A bare family expands to every supported locale in it,
        and which region wins is deterministic but arbitrary — so the response
        echoes the `locale` actually served. Read `locale`, never the request
        parameter, when labelling what the caller is hearing.

        404 means no preview audio has been generated for this voice in that
        locale — NOT that the voice cannot speak it. `supported_languages` on the
        voice is the claim about what it can speak; `preview_locales` is the list
        of locales this endpoint will succeed for. 404 is also returned when the
        voice does not exist, is not accessible to the caller's workspace, or is a
        platform voice from a provider that is not available to your account.

        Parameters
        ----------
        voice_id : str

        language : PreviewVoicesRequestLanguage
            BCP-47 language code, e.g. en-us, ko-kr

        model : typing.Optional[str]
            TTS model id, e.g. sonic-2

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseVoicePreviewOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/preview",
            method="GET",
            params={
                "language": language,
                "model": model,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoicePreviewOut,
                    parse_obj_as(
                        type_=ApiResponseVoicePreviewOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def favorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseVoiceOut]:
        """
        Add a voice to the current workspace's favorites.

        The response is a full `VoiceOut` and is narrowed exactly as `GET /voices/{voice_id}`
        is, so favoriting a voice never reveals locales the read endpoints hide. Note that
        favoriting a platform voice with no official locale succeeds but that voice will
        not appear under `?favorites_only=true`, which applies the same list restriction.

        Favorites are workspace-scoped, not per-user: all members of the workspace
        see the same favorited set. Idempotent — favoriting a voice that is already
        favorited succeeds without error. Returns the voice with `is_favorite=true`.
        Requires the caller to have at least editor role in the workspace. Returns
        404 for a platform voice from a provider that is not available to your
        account; voices your workspace owns can always be favorited.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseVoiceOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/favorite",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def unfavorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseDict]:
        """
        Remove a voice from the current workspace's favorites.

        Idempotent — removing a voice that is not currently favorited succeeds
        without error. Requires the caller to have at least editor role in the
        workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseDict]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/favorite",
            method="DELETE",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseDict,
                    parse_obj_as(
                        type_=ApiResponseDict,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawVoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        sort: typing.Optional[typing.Sequence[ListVoicesRequestSortItem]] = None,
        order: typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]] = None,
        buildable: typing.Optional[bool] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiCountedListResponseVoiceOut]:
        """
        List TTS voices available to the current workspace.

        Every filter accepts repeat-key OR semantics:
        `?gender=female&gender=neutral&category=narration&source=platform&source=workspace`.
        Filters combine across fields with AND; within a field, values OR.

        Hybrid search: when `search` is a non-empty string, semantic search is enabled
        for the deployment (`VOICE_SEMANTIC_SEARCH_ENABLED`), and the text embedder is
        available, `search` runs a hybrid of SEMANTIC relevance — meaning, not keywords, so
        "cheerful" also surfaces "bright/upbeat" voices, over the platform voices that carry a
        profile embedding — AND a keyword arm that matches the voice NAME (plus descriptor/tags),
        which also surfaces voices with no embedding and workspace-owned voices in scope, so a
        voice literally named by the query is found. Both arms honor the same filters and are
        fused into one ranking. In that mode `sort`/`order` are IGNORED (relevance order wins).
        If semantic search is disabled, the embedder is
        unavailable, or the embed call fails, `search` transparently falls back to the
        lexical name/tag/descriptor match described below — the response shape
        (`ApiCountedListResponse[VoiceOut]`) is identical either way.

        `language` matches a voice when any of its declared locales matches any
        requested value. A voice with no declared locales matches NO `language`
        filter — it must positively declare a locale to surface under it. This holds
        for platform and user-uploaded voices alike: an unclassified platform voice
        (catalog gap) is not treated as general-use, and a user-uploaded/cloned voice
        with no locale stays "language unknown" pending clone-flow detection.

        Passing `language` also fills `language_sample_url` on every row that has a clip
        in it — the same audio `GET /voices/{voice_id}/preview?language=` serves, so a
        caller auditioning a shortlist can play the locale-correct take straight from the
        list instead of a request per voice. `language_sample_locale` reports the region
        actually served. Both are null without the filter; `sample_url` is unaffected and
        still does not follow it.

        Platform voices are restricted to the officially supported locales: a platform
        voice that declares no official locale is not returned, and the locale arrays on
        the voices that are returned (`supported_languages`,
        `model_capabilities[].supported_languages`, `preview_locales`) list only official
        locales. A bare family code counts as official when the family is supported
        (`ko` qualifies because `ko-kr` is), matching the `language` filter above. Voices
        your workspace owns — imported, recorded, or uploaded — are exempt from both the
        exclusion and the narrowing: they routinely carry no declared locale at all, and
        hiding them would remove a customer's own voices from their own list.

        `buildable=true` narrows platform voices to the ones that can actually be
        SYNTHESIZED for `language`: the voice must have a measured `(provider, model, locale)`
        pair that clears the quality floors used by automatic voice selection, on a provider
        and model that are enabled, currently routable for synthesis, and carry a billable
        rate (or one your workspace holds a valid BYOK key for), and the voice must itself be
        able to speak that locale on that model.
        Without it the list is a raw catalogue browse that can return a voice a run would
        refuse — the same voice the assistant's own cards never offer. It **requires**
        `language` (422 otherwise): the measurements are per-locale, so "buildable" has no
        meaning until you say buildable for what. Repeating `language` asks whether the voice
        is buildable for AT LEAST ONE of them, and each locale is judged whole: a voice
        measured only for `en-us` is not returned for `?language=en-gb&language=en-us` unless
        it can speak `en-us` itself. Voices your workspace owns are returned
        either way — nothing measures a customer's own voice, so there is no pair to clear.
        `pagination.total` follows the same narrowing, so paging cannot walk past the gate.
        Transient provider health is deliberately NOT part of this filter; a vendor whose
        circuit breaker is open still lists. A vendor whose credentials cannot be resolved at
        all is a different case and IS excluded — that failure is not transient.

        `GET /voices/facets` does NOT take this parameter, so its chip counts are ungated and
        a chip can over-count relative to a `buildable=true` page. Gating them needs the
        LANGUAGE dimension evaluated per candidate locale — a language chip self-excludes the
        `language` filter this gate is defined against, so reusing the request's own locales
        would count every chip against the locale already selected — and that is a separate
        change from this one.

        Multi-sort: `sort` and `order` are parallel lists. `?sort=uses_count&sort=name&order=desc&order=asc`
        orders primarily by uses_count DESC, secondarily by name ASC. When `order`
        is shorter than `sort`, missing entries default per-field:
        `name=asc, created_at=desc, uses_count=desc`. When `sort` is omitted, list
        defaults to newest-first (or most-recently-favorited-first if
        `favorites_only=true`). Every sort path appends `Voice.id ASC` as a
        deterministic tiebreaker for pagination stability.

        Parameters
        ----------
        offset : typing.Optional[int]
            Number of results to skip for pagination.

        limit : typing.Optional[int]
            Maximum number of results to return (1–100).

        favorites_only : typing.Optional[bool]
            When true, return only voices in the workspace's favorites list.

        source : typing.Optional[typing.Sequence[ListVoicesRequestSourceItem]]
            Repeat for OR across scopes: `platform` for system-provided voices, `workspace` for workspace-owned voices.

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]
            Searches name, tags, and the voice's summary-derived descriptor text (closely tracks the served description; summary beyond 200 chars is not searched).

        sort : typing.Optional[typing.Sequence[ListVoicesRequestSortItem]]
            Repeat for multi-sort. Pairs with `order` index-wise.

        order : typing.Optional[typing.Sequence[ListVoicesRequestOrderItem]]
            Parallel to sort[]; shorter is padded with per-field defaults.

        buildable : typing.Optional[bool]
            Return only voices that can actually be synthesized for `language`: the measured quality floors, a provider/model that is enabled AND currently routable, and a billable rate (or your own BYOK key). Requires `language`; each repeated value is judged on its own. Voices your workspace owns are always returned.

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[ListVoicesRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiCountedListResponseVoiceOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/voices",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "favorites_only": favorites_only,
                "source": source,
                "gender": gender,
                "age": age,
                "category": category,
                "accent": accent,
                "search": search,
                "sort": sort,
                "order": order,
                "buildable": buildable,
                "provider": provider,
                "model": model,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiCountedListResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiCountedListResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_voice_facets(
        self,
        *,
        favorites_only: typing.Optional[bool] = None,
        source: typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]] = None,
        gender: typing.Optional[typing.Sequence[VoiceGender]] = None,
        age: typing.Optional[typing.Sequence[VoiceAge]] = None,
        category: typing.Optional[typing.Sequence[VoiceCategory]] = None,
        accent: typing.Optional[typing.Sequence[VoiceAccent]] = None,
        search: typing.Optional[str] = None,
        provider: typing.Optional[typing.Sequence[str]] = None,
        model: typing.Optional[typing.Sequence[str]] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseVoiceFacetsOut]:
        """
        Filter-bar options (chips) for the voice browser, one list per dimension.

        Returns `providers`, `models`, `languages` (data-driven) plus `genders`,
        `ages`, `categories`, `accents` (fixed enums) as `VoiceFacetItem[]` so the FE
        builds the whole filter bar — with per-chip count badges — in a single request
        instead of hardcoding option lists (mirrors `GET /dictionary/languages`). Each
        item is `{value, label, count}`: `value` is passed straight back to
        `GET /voices`; `label` is the display name for providers/models and `null`
        elsewhere (the FE owns language + enum labels); `count` is the number of
        matching voices. A language surfaces as one chip keyed by its canonical
        allowlist locale: every declared locale is folded onto the locale the
        `GET /voices` filter would match it against (bare `ko` and regioned `ko-kr`
        both count under `ko-kr`), so variants never split into duplicate chips for
        the identical filter. Model counts include only voices that explicitly declare
        the model. Language counts include voices that declare the exact regional locale
        plus voices that declare its bare family (`en` contributes to every supported
        `en-*` locale). A voice with no declared `supported_models` is "general use" —
        `GET /voices` matches it against every model filter but no `models` chip counts
        it, so a model chip's count can be lower than the `GET /voices?model=` result.
        Languages have no such gap: no-locale voices are excluded from both the language
        chips and `GET /voices?language=`, so language chip counts match the row counts.

        Accepts the SAME filters as `GET /voices` (tab scope `source`/`favorites_only`,
        plus `provider`/`model`/`language`/`gender`/`age`/`category`/`accent`/`search`).
        `count` is context-aware (faceted search): each dimension's counts apply every
        OTHER active filter but exclude that dimension's own selection — e.g. with
        `provider=elevenlabs` the language counts are scoped to ElevenLabs, while the
        provider chips still show every provider so the caller can switch.

        `search` follows the SAME two modes as `GET /voices` (see `_semantic_search_active`).
        In SEMANTIC mode (flag on, embedder available, platform in scope) the chips are
        counted over the population the semantic list can return — every active filter, plus
        "carries a description embedding OR is in the current ranked set" (the ANN only ranks
        embedded voices; the keyword arm contributes the rest) — so the chips describe the
        voices the list actually shows and never collapse to "No matches" on a query that has
        no literal name/tag hit. Per-dimension self-exclusion applies in full, exactly as in
        lexical mode. Counts are clamped to `VOICE_SEARCH_MAX_RANKED`, because the semantic
        list's `pagination.total` is that same capped ranked-set size — so a chip's `count` is
        the number of rows `GET /voices` returns once that value is selected. Two bounded
        exceptions: a voice reachable only through the keyword arm is counted only under the
        value already selected (the ranked set is computed under the current filters), and
        ANN recall can return fewer rows than the chip promises. In the LEXICAL
        fallback (flag off / no embedder / non-platform source / embed fault) `search` is the
        `name`/`descriptor`/`tags` ILIKE and counts are exact (no cap), exactly as before.

        No `buildable` parameter: unlike `GET /voices` these counts are NOT narrowed to
        synthesizable voices, so against a `buildable=true` page a chip can over-count. The
        language dimension is why — a language chip deliberately self-excludes the `language`
        filter that gate is defined against, so it has to be evaluated per candidate locale
        rather than against the request's own, and the legacy-JSONB half of the language count
        is aggregated in Python with no query to attach it to.

        Chips are drawn from the same population `GET /voices` returns, so the
        official-locale restriction applies here too and no chip can open an empty page.
        For the `model` dimension the restriction is evaluated per capability row rather
        than per voice — a voice whose only official locale sits on a sibling model does
        not count toward this model's chip, because `GET /voices?model=` would not return
        it either.

        Count-0 policy: data-driven dimensions omit count-0 values (only present ones,
        each a valid `GET /voices` filter — providers/models restricted to the enabled
        catalog, languages to the supported-locale allowlist, so a chip never 422s).
        Enum dimensions always return the full enum in natural order, count-0 included,
        for the FE to grey out.

        Parameters
        ----------
        favorites_only : typing.Optional[bool]
            Favorites tab scope

        source : typing.Optional[typing.Sequence[GetVoiceFacetsApiV1VoicesFacetsGetRequestSourceItem]]
            Tab scope — repeat for OR, same values as GET /voices (e.g. platform, workspace)

        gender : typing.Optional[typing.Sequence[VoiceGender]]
            Repeat for OR

        age : typing.Optional[typing.Sequence[VoiceAge]]
            Repeat for OR

        category : typing.Optional[typing.Sequence[VoiceCategory]]
            Repeat for OR

        accent : typing.Optional[typing.Sequence[VoiceAccent]]
            Repeat for OR

        search : typing.Optional[str]

        provider : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?provider=elevenlabs&provider=rime

        model : typing.Optional[typing.Sequence[str]]
            Repeat for OR. Filters platform voices by TTS model, e.g. ?model=arcana&model=sonic-2

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseVoiceFacetsOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/voices/facets",
            method="GET",
            params={
                "favorites_only": favorites_only,
                "source": source,
                "gender": gender,
                "age": age,
                "category": category,
                "accent": accent,
                "search": search,
                "provider": provider,
                "model": model,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceFacetsOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceFacetsOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseVoiceOut]:
        """
        Fetch a single voice by its ID.

        Returns both platform (system-wide) voices and voices that belong to the
        caller's workspace. Returns 404 when the voice does not exist, is not
        accessible to the caller's workspace, or is a platform voice from a provider
        that is not available to your account. Voices your workspace owns stay
        readable regardless of provider availability. The `sample_url` field is a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term. This endpoint sets
        `Cache-Control: no-store` because the response bakes in that short-lived
        presigned URL — server-side (Redis) caching still applies underneath.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseVoiceOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def similar(
        self,
        voice_id: str,
        *,
        limit: typing.Optional[int] = None,
        language: typing.Optional[typing.Sequence[str]] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiListResponseVoiceSimilarOut]:
        """
        Return voices acoustically similar to a reference voice.

        Results are ranked by semantic similarity score (descending) and include the
        reference voice's workspace voices and all platform voices. Each result
        includes a `similarity_score` between 0 and 1. Optionally filter by one or
        more `language` BCP-47 codes (repeat the parameter for OR semantics); up to
        16 language values are accepted. Results are restricted to officially supported
        locales on the same terms as `GET /voices`; the reference voice itself is not,
        so you can ask for neighbours of a voice that no longer appears in the list.
        Returns 503 when the reference voice has no embedding yet — retry after the
        indicated `Retry-After` interval. Prefer this
        endpoint over `GET /voices` with manual filtering when building a
        "voices like this" recommendation UI.

        Platform voices from providers that are not available to your account are
        rejected as a reference (404) and omitted from the results; voices your
        workspace owns are unaffected. This endpoint sets `Cache-Control: no-store`
        because the response bakes in short-lived presigned sample URLs — server-side
        (Redis) caching still applies underneath for the default `limit`/`language` shape.

        Parameters
        ----------
        voice_id : str

        limit : typing.Optional[int]
            Number of similar voices to return (1–50).

        language : typing.Optional[typing.Sequence[str]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiListResponseVoiceSimilarOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/similar",
            method="GET",
            params={
                "limit": limit,
                "language": language,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseVoiceSimilarOut,
                    parse_obj_as(
                        type_=ApiListResponseVoiceSimilarOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def preview(
        self,
        voice_id: str,
        *,
        language: PreviewVoicesRequestLanguage,
        model: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseVoicePreviewOut]:
        """
        Fetch ready-to-play preview audio for one voice in one language.

        Returns the voice's `name`, the preview's `locale`, the `model` it was
        synthesized with, its stored `content_type`, and a `sample_url` — a
        time-limited presigned URL valid for 1 hour; regenerate it by calling this
        endpoint again rather than caching it long-term. Pass `model` to prefer a
        specific TTS model; a preview from another model is still returned when
        that model has none.

        `language` accepts a bare family (`ko`, `en`) as well as an exact locale
        (`ko-kr`, `en-gb`). A bare family expands to every supported locale in it,
        and which region wins is deterministic but arbitrary — so the response
        echoes the `locale` actually served. Read `locale`, never the request
        parameter, when labelling what the caller is hearing.

        404 means no preview audio has been generated for this voice in that
        locale — NOT that the voice cannot speak it. `supported_languages` on the
        voice is the claim about what it can speak; `preview_locales` is the list
        of locales this endpoint will succeed for. 404 is also returned when the
        voice does not exist, is not accessible to the caller's workspace, or is a
        platform voice from a provider that is not available to your account.

        Parameters
        ----------
        voice_id : str

        language : PreviewVoicesRequestLanguage
            BCP-47 language code, e.g. en-us, ko-kr

        model : typing.Optional[str]
            TTS model id, e.g. sonic-2

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseVoicePreviewOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/preview",
            method="GET",
            params={
                "language": language,
                "model": model,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoicePreviewOut,
                    parse_obj_as(
                        type_=ApiResponseVoicePreviewOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def favorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseVoiceOut]:
        """
        Add a voice to the current workspace's favorites.

        The response is a full `VoiceOut` and is narrowed exactly as `GET /voices/{voice_id}`
        is, so favoriting a voice never reveals locales the read endpoints hide. Note that
        favoriting a platform voice with no official locale succeeds but that voice will
        not appear under `?favorites_only=true`, which applies the same list restriction.

        Favorites are workspace-scoped, not per-user: all members of the workspace
        see the same favorited set. Idempotent — favoriting a voice that is already
        favorited succeeds without error. Returns the voice with `is_favorite=true`.
        Requires the caller to have at least editor role in the workspace. Returns
        404 for a platform voice from a provider that is not available to your
        account; voices your workspace owns can always be favorited.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseVoiceOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/favorite",
            method="POST",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseVoiceOut,
                    parse_obj_as(
                        type_=ApiResponseVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def unfavorite_voice(
        self,
        voice_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseDict]:
        """
        Remove a voice from the current workspace's favorites.

        Idempotent — removing a voice that is not currently favorited succeeds
        without error. Requires the caller to have at least editor role in the
        workspace.

        Parameters
        ----------
        voice_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseDict]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/voices/{encode_path_param(voice_id)}/favorite",
            method="DELETE",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseDict,
                    parse_obj_as(
                        type_=ApiResponseDict,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
