# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_response_auth_whoami_out import ApiResponseAuthWhoamiOut
from .raw_client import AsyncRawAuthClient, RawAuthClient


class AuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthClient
        """
        return self._raw_client

    def whoami(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseAuthWhoamiOut:
        """
        Return the resolved authentication context for the current credential.

        Useful for verifying that a Bearer JWT or API key is valid and discovering
        which workspace and permission scopes it grants — call this first when
        debugging authentication issues or bootstrapping an SDK integration.

        The `auth_kind` field indicates whether the credential is a session token
        (`clerk`) or a programmatic key (`api_key`). For API keys, `workspace_id`
        and `api_key_id` are always populated; for session tokens, `workspace_id`
        reflects the `X-Workspace-Id` header value (if present) and `api_key_id`
        is `null`. The `scopes` list is sorted and deduplicated.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseAuthWhoamiOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.auth.whoami()
        """
        _response = self._raw_client.whoami(request_options=request_options)
        return _response.data


class AsyncAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthClient
        """
        return self._raw_client

    async def whoami(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseAuthWhoamiOut:
        """
        Return the resolved authentication context for the current credential.

        Useful for verifying that a Bearer JWT or API key is valid and discovering
        which workspace and permission scopes it grants — call this first when
        debugging authentication issues or bootstrapping an SDK integration.

        The `auth_kind` field indicates whether the credential is a session token
        (`clerk`) or a programmatic key (`api_key`). For API keys, `workspace_id`
        and `api_key_id` are always populated; for session tokens, `workspace_id`
        reflects the `X-Workspace-Id` header value (if present) and `api_key_id`
        is `null`. The `scopes` list is sorted and deduplicated.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseAuthWhoamiOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.auth.whoami()


        asyncio.run(main())
        """
        _response = await self._raw_client.whoami(request_options=request_options)
        return _response.data
