# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_response_dict import ApiResponseDict
from ..types.api_response_upload_create_response import ApiResponseUploadCreateResponse
from ..types.api_response_upload_out import ApiResponseUploadOut
from .raw_client import AsyncRawUploadsClient, RawUploadsClient
from .types.upload_confirm_request_context_type import UploadConfirmRequestContextType
from .types.upload_request_category import UploadRequestCategory

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UploadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUploadsClient
        """
        return self._raw_client

    def create(
        self,
        *,
        filename: str,
        category: UploadRequestCategory,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseUploadCreateResponse:
        """
        Request a presigned URL to upload a file to object storage (step 1 of 2).

        The two-step upload flow:
        1. `POST /uploads` — register the file and receive a short-lived `upload_url`.
           PUT your file bytes directly to that URL (do not send them to this API).
        2. `POST /uploads/{id}` — confirm the upload completed and bind the file to a
           resource (e.g. a workflow). The file is moved to its final location and the
           upload record transitions from `pending` to `uploaded`.

        `category` controls which file formats are accepted:
        - `script` — text-based formats (txt, srt, csv, json, xliff, docx)
        - `dictionary` — audio formats (mp3, wav, m4a, ogg, webm)

        The presigned URL expires within a short window (see `upload_url` TTL in the
        response). If the URL expires before the PUT completes, discard this upload
        record and start over with a fresh `POST /uploads` call.

        `X-Workspace-Id` is optional but recommended for workspace-scoped storage
        quota tracking. API keys with a bound workspace attach automatically.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        filename : str
            Original filename including extension (e.g. `script.txt`). Must include a file extension.

        category : UploadRequestCategory
            File category. Determines which formats are accepted: `script` for text formats (txt, srt, csv, json, xliff, docx); `dictionary` for audio formats (mp3, wav, m4a, ogg, webm).

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseUploadCreateResponse
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.uploads.create(
            filename="filename",
            category="script",
        )
        """
        _response = self._raw_client.create(
            filename=filename, category=category, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def confirm(
        self,
        upload_id: str,
        *,
        context_type: UploadConfirmRequestContextType,
        context_id: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseUploadOut:
        """
        Confirm a completed upload and bind it to a resource (step 2 of 2).

        Call this after successfully PUTting your file to the presigned URL returned
        by `POST /uploads`. Provide `context_type` and `context_id` to associate the
        file with an existing resource (currently `workflow` is the supported context
        type). The file is moved to its final location and `status` transitions from
        `pending` to `uploaded`.

        This endpoint is idempotent: if the upload was already confirmed, the current
        state is returned without re-processing.

        Storage quota is checked against the workspace at confirm time. If confirming
        would exceed the workspace storage limit, a 402 is returned and the file
        remains in its staging location (the upload record stays `pending` so you can
        delete the staging file and try a smaller file).

        Binding to a workspace-scoped resource requires the caller to be a member of
        that workspace. Workspace is inferred from the resource when `X-Workspace-Id`
        is omitted.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        upload_id : str

        context_type : UploadConfirmRequestContextType
            Type of resource this upload is being attached to: `workflow`, `playground`, or `assistant_session`.

        context_id : str
            ID of the resource to attach this upload to. Must be an existing resource of the given `context_type` that the caller has access to.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseUploadOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.uploads.confirm(
            upload_id="upload_id",
            context_type="workflow",
            context_id="context_id",
        )
        """
        _response = self._raw_client.confirm(
            upload_id,
            context_type=context_type,
            context_id=context_id,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        upload_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Delete an upload and its associated file.

        Permanently removes the upload record and schedules the stored file for
        deletion. The record is removed first; the file is cleaned up asynchronously
        after the response so storage removal only happens after a successful commit.

        If the upload was previously confirmed against a workspace-scoped resource,
        the consumed storage bytes are released back to the workspace quota, keeping
        the workspace storage counter accurate.

        Callers can delete uploads in any state (`pending` or `uploaded`). Deleting
        a `pending` upload (e.g. after an expired presigned URL) is the correct way
        to clean up an abandoned upload attempt.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        upload_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.uploads.delete(
            upload_id="upload_id",
        )
        """
        _response = self._raw_client.delete(upload_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data


class AsyncUploadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUploadsClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        filename: str,
        category: UploadRequestCategory,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseUploadCreateResponse:
        """
        Request a presigned URL to upload a file to object storage (step 1 of 2).

        The two-step upload flow:
        1. `POST /uploads` — register the file and receive a short-lived `upload_url`.
           PUT your file bytes directly to that URL (do not send them to this API).
        2. `POST /uploads/{id}` — confirm the upload completed and bind the file to a
           resource (e.g. a workflow). The file is moved to its final location and the
           upload record transitions from `pending` to `uploaded`.

        `category` controls which file formats are accepted:
        - `script` — text-based formats (txt, srt, csv, json, xliff, docx)
        - `dictionary` — audio formats (mp3, wav, m4a, ogg, webm)

        The presigned URL expires within a short window (see `upload_url` TTL in the
        response). If the URL expires before the PUT completes, discard this upload
        record and start over with a fresh `POST /uploads` call.

        `X-Workspace-Id` is optional but recommended for workspace-scoped storage
        quota tracking. API keys with a bound workspace attach automatically.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        filename : str
            Original filename including extension (e.g. `script.txt`). Must include a file extension.

        category : UploadRequestCategory
            File category. Determines which formats are accepted: `script` for text formats (txt, srt, csv, json, xliff, docx); `dictionary` for audio formats (mp3, wav, m4a, ogg, webm).

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseUploadCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.uploads.create(
                filename="filename",
                category="script",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            filename=filename, category=category, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def confirm(
        self,
        upload_id: str,
        *,
        context_type: UploadConfirmRequestContextType,
        context_id: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseUploadOut:
        """
        Confirm a completed upload and bind it to a resource (step 2 of 2).

        Call this after successfully PUTting your file to the presigned URL returned
        by `POST /uploads`. Provide `context_type` and `context_id` to associate the
        file with an existing resource (currently `workflow` is the supported context
        type). The file is moved to its final location and `status` transitions from
        `pending` to `uploaded`.

        This endpoint is idempotent: if the upload was already confirmed, the current
        state is returned without re-processing.

        Storage quota is checked against the workspace at confirm time. If confirming
        would exceed the workspace storage limit, a 402 is returned and the file
        remains in its staging location (the upload record stays `pending` so you can
        delete the staging file and try a smaller file).

        Binding to a workspace-scoped resource requires the caller to be a member of
        that workspace. Workspace is inferred from the resource when `X-Workspace-Id`
        is omitted.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        upload_id : str

        context_type : UploadConfirmRequestContextType
            Type of resource this upload is being attached to: `workflow`, `playground`, or `assistant_session`.

        context_id : str
            ID of the resource to attach this upload to. Must be an existing resource of the given `context_type` that the caller has access to.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseUploadOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.uploads.confirm(
                upload_id="upload_id",
                context_type="workflow",
                context_id="context_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.confirm(
            upload_id,
            context_type=context_type,
            context_id=context_id,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        upload_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Delete an upload and its associated file.

        Permanently removes the upload record and schedules the stored file for
        deletion. The record is removed first; the file is cleaned up asynchronously
        after the response so storage removal only happens after a successful commit.

        If the upload was previously confirmed against a workspace-scoped resource,
        the consumed storage bytes are released back to the workspace quota, keeping
        the workspace storage counter accurate.

        Callers can delete uploads in any state (`pending` or `uploaded`). Deleting
        a `pending` upload (e.g. after an expired presigned URL) is the correct way
        to clean up an abandoned upload attempt.

        Dual-auth: Bearer JWT or API key (scope `uploads:write`).

        Parameters
        ----------
        upload_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.uploads.delete(
                upload_id="upload_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(upload_id, workspace_id=workspace_id, request_options=request_options)
        return _response.data
