# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_list_response_dictionary_out import ApiListResponseDictionaryOut
from ..types.api_response_dict import ApiResponseDict
from ..types.api_response_dictionary_out import ApiResponseDictionaryOut
from ..types.api_response_list_dictionary_language_out import ApiResponseListDictionaryLanguageOut
from ..types.api_response_pronunciation_suggestion import ApiResponsePronunciationSuggestion
from ..types.dictionary_method import DictionaryMethod
from .raw_client import AsyncRawDictionaryClient, RawDictionaryClient
from .types.list_dictionary_entries_api_v1dictionary_get_request_language import (
    ListDictionaryEntriesApiV1DictionaryGetRequestLanguage,
)
from .types.list_dictionary_entries_api_v1dictionary_get_request_order import (
    ListDictionaryEntriesApiV1DictionaryGetRequestOrder,
)
from .types.list_dictionary_entries_api_v1dictionary_get_request_sort import (
    ListDictionaryEntriesApiV1DictionaryGetRequestSort,
)
from .types.search_dictionary_entries_api_v1dictionary_search_get_request_language_item import (
    SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem,
)
from .types.search_dictionary_entries_api_v1dictionary_search_get_request_order import (
    SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder,
)
from .types.search_dictionary_entries_api_v1dictionary_search_get_request_sort import (
    SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DictionaryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDictionaryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDictionaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDictionaryClient
        """
        return self._raw_client

    def list_dictionary_entries(
        self,
        *,
        language: ListDictionaryEntriesApiV1DictionaryGetRequestLanguage,
        method: typing.Optional[typing.Sequence[DictionaryMethod]] = None,
        sort: typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestSort] = None,
        order: typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestOrder] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseDictionaryOut:
        """
        List dictionary entries for a single language in the current workspace.

        Parameters
        ----------
        language : ListDictionaryEntriesApiV1DictionaryGetRequestLanguage
            BCP-47 language code, e.g. en-us, ko-kr

        method : typing.Optional[typing.Sequence[DictionaryMethod]]
            Repeat for OR, e.g. ?method=spelled&method=recorded

        sort : typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestSort]

        order : typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestOrder]

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseDictionaryOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.list_dictionary_entries(
            language="de-de",
        )
        """
        _response = self._raw_client.list_dictionary_entries(
            language=language,
            method=method,
            sort=sort,
            order=order,
            offset=offset,
            limit=limit,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    def create_dictionary_entry(
        self,
        *,
        word: str,
        method: DictionaryMethod,
        language: str,
        workspace_id: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        pronunciation: typing.Optional[str] = OMIT,
        upload_id: typing.Optional[str] = OMIT,
        ipa: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDictionaryOut:
        """
        Create a new dictionary entry in the current workspace.

        Parameters
        ----------
        word : str

        method : DictionaryMethod

        language : str

        workspace_id : typing.Optional[str]

        description : typing.Optional[str]

        pronunciation : typing.Optional[str]

        upload_id : typing.Optional[str]

        ipa : typing.Optional[str]
            User-provided IPA transcription. Persisted as-is. Auto-generation via phonemizer/LLM is a POD-256 follow-up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDictionaryOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.create_dictionary_entry(
            word="word",
            method="spelled",
            language="language",
        )
        """
        _response = self._raw_client.create_dictionary_entry(
            word=word,
            method=method,
            language=language,
            workspace_id=workspace_id,
            description=description,
            pronunciation=pronunciation,
            upload_id=upload_id,
            ipa=ipa,
            request_options=request_options,
        )
        return _response.data

    def search_dictionary_entries(
        self,
        *,
        search: str,
        sort: typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort] = None,
        order: typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        language: typing.Optional[
            typing.Sequence[SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem]
        ] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseDictionaryOut:
        """
        Cross-language search over dictionary entries.

        Parameters
        ----------
        search : str

        sort : typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort]

        order : typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder]

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        language : typing.Optional[typing.Sequence[SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseDictionaryOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.search_dictionary_entries(
            search="search",
        )
        """
        _response = self._raw_client.search_dictionary_entries(
            search=search,
            sort=sort,
            order=order,
            offset=offset,
            limit=limit,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    def list_dictionary_languages(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseListDictionaryLanguageOut:
        """
        Return distinct languages with entry counts, ordered by count DESC, code ASC.

        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseListDictionaryLanguageOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.list_dictionary_languages()
        """
        _response = self._raw_client.list_dictionary_languages(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def suggest_pronunciation(
        self,
        *,
        word: str,
        language: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponsePronunciationSuggestion:
        """
        Return a deterministic FE-parity pronunciation fallback.

        ``language`` is reserved for future per-locale rules; ``ipa`` is reserved
        for a future generator and is always ``None`` in this version.

        Workspace scoping is enforced via ``get_current_workspace`` even though the
        response is workspace-independent today: this keeps all ``/api/v1/``
        endpoints uniform (see CLAUDE.md §Workspace Scoping) and leaves room for
        per-workspace dictionary overrides when the generator lands.

        Parameters
        ----------
        word : str

        language : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponsePronunciationSuggestion
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.suggest_pronunciation(
            word="word",
            language="language",
        )
        """
        _response = self._raw_client.suggest_pronunciation(
            word=word, language=language, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def update_dictionary_entry(
        self,
        entry_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        word: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        pronunciation: typing.Optional[str] = OMIT,
        upload_id: typing.Optional[str] = OMIT,
        method: typing.Optional[DictionaryMethod] = OMIT,
        language: typing.Optional[str] = OMIT,
        ipa: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDictionaryOut:
        """
        Update a dictionary entry scoped to the current workspace.

        Parameters
        ----------
        entry_id : str

        workspace_id : typing.Optional[str]

        word : typing.Optional[str]

        description : typing.Optional[str]

        pronunciation : typing.Optional[str]

        upload_id : typing.Optional[str]

        method : typing.Optional[DictionaryMethod]

        language : typing.Optional[str]

        ipa : typing.Optional[str]
            User-provided IPA transcription. Persisted as-is. Auto-generation via phonemizer/LLM is a POD-256 follow-up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDictionaryOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.update_dictionary_entry(
            entry_id="entry_id",
        )
        """
        _response = self._raw_client.update_dictionary_entry(
            entry_id,
            workspace_id=workspace_id,
            word=word,
            description=description,
            pronunciation=pronunciation,
            upload_id=upload_id,
            method=method,
            language=language,
            ipa=ipa,
            request_options=request_options,
        )
        return _response.data

    def delete_dictionary_entry(
        self,
        entry_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Soft-delete a dictionary entry scoped to the current workspace.

        Parameters
        ----------
        entry_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.dictionary.delete_dictionary_entry(
            entry_id="entry_id",
        )
        """
        _response = self._raw_client.delete_dictionary_entry(
            entry_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncDictionaryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDictionaryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDictionaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDictionaryClient
        """
        return self._raw_client

    async def list_dictionary_entries(
        self,
        *,
        language: ListDictionaryEntriesApiV1DictionaryGetRequestLanguage,
        method: typing.Optional[typing.Sequence[DictionaryMethod]] = None,
        sort: typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestSort] = None,
        order: typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestOrder] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseDictionaryOut:
        """
        List dictionary entries for a single language in the current workspace.

        Parameters
        ----------
        language : ListDictionaryEntriesApiV1DictionaryGetRequestLanguage
            BCP-47 language code, e.g. en-us, ko-kr

        method : typing.Optional[typing.Sequence[DictionaryMethod]]
            Repeat for OR, e.g. ?method=spelled&method=recorded

        sort : typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestSort]

        order : typing.Optional[ListDictionaryEntriesApiV1DictionaryGetRequestOrder]

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseDictionaryOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.list_dictionary_entries(
                language="de-de",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_dictionary_entries(
            language=language,
            method=method,
            sort=sort,
            order=order,
            offset=offset,
            limit=limit,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    async def create_dictionary_entry(
        self,
        *,
        word: str,
        method: DictionaryMethod,
        language: str,
        workspace_id: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        pronunciation: typing.Optional[str] = OMIT,
        upload_id: typing.Optional[str] = OMIT,
        ipa: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDictionaryOut:
        """
        Create a new dictionary entry in the current workspace.

        Parameters
        ----------
        word : str

        method : DictionaryMethod

        language : str

        workspace_id : typing.Optional[str]

        description : typing.Optional[str]

        pronunciation : typing.Optional[str]

        upload_id : typing.Optional[str]

        ipa : typing.Optional[str]
            User-provided IPA transcription. Persisted as-is. Auto-generation via phonemizer/LLM is a POD-256 follow-up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDictionaryOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.create_dictionary_entry(
                word="word",
                method="spelled",
                language="language",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_dictionary_entry(
            word=word,
            method=method,
            language=language,
            workspace_id=workspace_id,
            description=description,
            pronunciation=pronunciation,
            upload_id=upload_id,
            ipa=ipa,
            request_options=request_options,
        )
        return _response.data

    async def search_dictionary_entries(
        self,
        *,
        search: str,
        sort: typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort] = None,
        order: typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        language: typing.Optional[
            typing.Sequence[SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem]
        ] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseDictionaryOut:
        """
        Cross-language search over dictionary entries.

        Parameters
        ----------
        search : str

        sort : typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort]

        order : typing.Optional[SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder]

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        language : typing.Optional[typing.Sequence[SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem]]
            Repeat for OR, e.g. ?language=en-us&language=ko-kr

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseDictionaryOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.search_dictionary_entries(
                search="search",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_dictionary_entries(
            search=search,
            sort=sort,
            order=order,
            offset=offset,
            limit=limit,
            language=language,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data

    async def list_dictionary_languages(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseListDictionaryLanguageOut:
        """
        Return distinct languages with entry counts, ordered by count DESC, code ASC.

        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseListDictionaryLanguageOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.list_dictionary_languages()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_dictionary_languages(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def suggest_pronunciation(
        self,
        *,
        word: str,
        language: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponsePronunciationSuggestion:
        """
        Return a deterministic FE-parity pronunciation fallback.

        ``language`` is reserved for future per-locale rules; ``ipa`` is reserved
        for a future generator and is always ``None`` in this version.

        Workspace scoping is enforced via ``get_current_workspace`` even though the
        response is workspace-independent today: this keeps all ``/api/v1/``
        endpoints uniform (see CLAUDE.md §Workspace Scoping) and leaves room for
        per-workspace dictionary overrides when the generator lands.

        Parameters
        ----------
        word : str

        language : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponsePronunciationSuggestion
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.suggest_pronunciation(
                word="word",
                language="language",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.suggest_pronunciation(
            word=word, language=language, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def update_dictionary_entry(
        self,
        entry_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        word: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        pronunciation: typing.Optional[str] = OMIT,
        upload_id: typing.Optional[str] = OMIT,
        method: typing.Optional[DictionaryMethod] = OMIT,
        language: typing.Optional[str] = OMIT,
        ipa: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDictionaryOut:
        """
        Update a dictionary entry scoped to the current workspace.

        Parameters
        ----------
        entry_id : str

        workspace_id : typing.Optional[str]

        word : typing.Optional[str]

        description : typing.Optional[str]

        pronunciation : typing.Optional[str]

        upload_id : typing.Optional[str]

        method : typing.Optional[DictionaryMethod]

        language : typing.Optional[str]

        ipa : typing.Optional[str]
            User-provided IPA transcription. Persisted as-is. Auto-generation via phonemizer/LLM is a POD-256 follow-up.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDictionaryOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.update_dictionary_entry(
                entry_id="entry_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_dictionary_entry(
            entry_id,
            workspace_id=workspace_id,
            word=word,
            description=description,
            pronunciation=pronunciation,
            upload_id=upload_id,
            method=method,
            language=language,
            ipa=ipa,
            request_options=request_options,
        )
        return _response.data

    async def delete_dictionary_entry(
        self,
        entry_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseDict:
        """
        Soft-delete a dictionary entry scoped to the current workspace.

        Parameters
        ----------
        entry_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.dictionary.delete_dictionary_entry(
                entry_id="entry_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_dictionary_entry(
            entry_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
