# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_list_response_plan_response import ApiListResponsePlanResponse
from ..types.api_response_checkout_response import ApiResponseCheckoutResponse
from ..types.api_response_plan_change_preview_response import ApiResponsePlanChangePreviewResponse
from .raw_client import AsyncRawBillingClient, RawBillingClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def list_plans(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiListResponsePlanResponse:
        """
        List available subscription plans.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponsePlanResponse
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.billing.list_plans()
        """
        _response = self._raw_client.list_plans(request_options=request_options)
        return _response.data

    def preview_plan_change(
        self, plan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponsePlanChangePreviewResponse:
        """
        Preview the cost of changing to the given plan.

        Parameters
        ----------
        plan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponsePlanChangePreviewResponse
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.billing.preview_plan_change(
            plan_id="plan_id",
        )
        """
        _response = self._raw_client.preview_plan_change(plan_id, request_options=request_options)
        return _response.data

    def create_checkout(
        self, *, plan_id: str, return_url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseCheckoutResponse:
        """
        Create a Stripe Checkout session for the given plan.

        Parameters
        ----------
        plan_id : str

        return_url : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseCheckoutResponse
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.billing.create_checkout(
            plan_id="plan_id",
            return_url="return_url",
        )
        """
        _response = self._raw_client.create_checkout(
            plan_id=plan_id, return_url=return_url, request_options=request_options
        )
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def list_plans(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiListResponsePlanResponse:
        """
        List available subscription plans.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponsePlanResponse
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.billing.list_plans()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_plans(request_options=request_options)
        return _response.data

    async def preview_plan_change(
        self, plan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponsePlanChangePreviewResponse:
        """
        Preview the cost of changing to the given plan.

        Parameters
        ----------
        plan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponsePlanChangePreviewResponse
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.billing.preview_plan_change(
                plan_id="plan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_plan_change(plan_id, request_options=request_options)
        return _response.data

    async def create_checkout(
        self, *, plan_id: str, return_url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseCheckoutResponse:
        """
        Create a Stripe Checkout session for the given plan.

        Parameters
        ----------
        plan_id : str

        return_url : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseCheckoutResponse
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.billing.create_checkout(
                plan_id="plan_id",
                return_url="return_url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_checkout(
            plan_id=plan_id, return_url=return_url, request_options=request_options
        )
        return _response.data
