# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .meta import Meta
from .pagination_meta import PaginationMeta
from .plan_response import PlanResponse


class ApiListResponsePlanResponse(UniversalBaseModel):
    data: typing.List[PlanResponse]
    meta: Meta
    pagination: PaginationMeta

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
