# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_key_scope import ApiKeyScope


class ApiKeyOut(UniversalBaseModel):
    id: str
    workspace_id: str
    created_by: typing.Optional[str] = None
    name: str
    key_type: str
    key_prefix: str
    key_suffix: str
    scopes: typing.List[ApiKeyScope]
    active: bool
    last_used_at: typing.Optional[dt.datetime] = None
    rate_limit_per_min: typing.Optional[int] = None
    revoked_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    preview: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
