# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .catalog_link import CatalogLink


class CatalogProviderOut(UniversalBaseModel):
    """
    Catalog provider entry — lean, customer-safe.

    Sourced from the in-memory ``ProviderRegistry`` (TTS / ``processing`` kind).
    Cost, credentials, base_url, and enabled flags are excluded by construction.
    """

    provider: str
    display_name: str
    kind: str
    model_count: int
    links: typing.Optional[typing.Dict[str, CatalogLink]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
