# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .catalog_link import CatalogLink


class CatalogModelOut(UniversalBaseModel):
    """
    Catalog model entry — lean, customer-safe.

    ``config_schema`` is the per-model TTS config JSON-schema (from the provider
    registry's Pydantic config class). ``voice_count`` is the number of active
    platform voices catalogued under this exact ``(provider, model)``.
    """

    model: str
    display_name: str
    content_type: typing.Optional[str] = None
    config_schema: typing.Optional[typing.Dict[str, typing.Any]] = None
    voice_count: int
    links: typing.Optional[typing.Dict[str, CatalogLink]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
