# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GraphEdge(UniversalBaseModel):
    id: str
    source: str
    source_port: typing_extensions.Annotated[str, FieldMetadata(alias="sourcePort"), pydantic.Field(alias="sourcePort")]
    target: str
    target_port: typing_extensions.Annotated[str, FieldMetadata(alias="targetPort"), pydantic.Field(alias="targetPort")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
