# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .node_option_property import NodeOptionProperty


class NodeOptionHref(UniversalBaseModel):
    """
    HAL-FORMS-flavored HATEOAS link entry in `options`.
    """

    target: str
    method: typing.Optional[str] = None
    properties: typing.Optional[typing.Dict[str, NodeOptionProperty]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
