# This file was auto-generated by Fern from our API Definition.

import typing

NodeType = typing.Union[
    typing.Literal[
        "source_script",
        "operator_translator",
        "operator_normalizer",
        "operator_generator",
        "operator_phoneme_injector",
        "sink_preview",
        "validator_error_rate",
        "validator_naturalness",
        "validator_noise",
        "validator_pronunciation",
        "operator_pronunciation_corrector",
    ],
    typing.Any,
]
