# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RunStatusCounts(UniversalBaseModel):
    """
    Per-raw-``RunStatus`` run counts for a workflow.

    Computed over ALL runs of the workflow — the same population as ``runs_count`` —
    so it is NOT affected by the list-level ``status`` filter. Every raw status is
    always present; a status with no runs is ``0``. The sum of all fields equals
    ``runs_count``, and each field matches the ``pagination.total`` of
    ``GET /workflows/{id}/runs?status=<status>``. These are RAW status counts (not the
    UI-derived ``WorkflowListStatus`` buckets), so the caller can group them per tab.
    """

    pending: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs queued but not yet started.
    """

    running: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs currently executing.
    """

    completed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs that finished successfully.
    """

    failed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs that ended in a failure state.
    """

    cancelled: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs explicitly cancelled by a user.
    """

    paused: typing.Optional[int] = pydantic.Field(default=None)
    """
    Runs currently paused/parked.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
