# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TriggeredByOut(UniversalBaseModel):
    """
    Actor that triggered a workflow run.

    ``user_name`` is guaranteed non-empty: derived from
    ``the user display name`` which falls back to ``email``
    when both first/last names are empty (``email`` is NOT NULL on User).
    """

    user_id: str
    user_name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
