# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UploadOut(UniversalBaseModel):
    id: str
    user_id: str
    workspace_id: typing.Optional[str] = None
    filename: str
    category: str
    content_type: str
    format: typing.Optional[str] = None
    status: str
    size_bytes: typing.Optional[int] = None
    download_url: typing.Optional[str] = None
    context_type: typing.Optional[str] = None
    context_id: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
