# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_by_language_out_activity_view import UsageByLanguageOutActivityView
from .usage_by_language_out_range import UsageByLanguageOutRange
from .usage_language_row_out import UsageLanguageRowOut
from .usage_period_out import UsagePeriodOut


class UsageByLanguageOut(UniversalBaseModel):
    range: typing.Optional[UsageByLanguageOutRange] = pydantic.Field(default=None)
    """
    Rolling range used for rows, or null when activity_view supplies the effective period.
    """

    activity_view: typing.Optional[UsageByLanguageOutActivityView] = None
    timezone: str
    period: UsagePeriodOut
    languages: typing.Optional[typing.List[UsageLanguageRowOut]] = None
    total_credits: typing.Optional[int] = None
    untagged_credits: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
