# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UsageLanguageRowOut(UniversalBaseModel):
    locale_code: str = pydantic.Field()
    """
    BCP-47 locale code (e.g. `en-us`, `ko-kr`).
    """

    display_name: str = pydantic.Field()
    """
    Human-readable language name (e.g. `English (US)`).
    """

    share: float = pydantic.Field()
    """
    Fractional share of workspace usage in the range 0..1; multiply by 100 for percent display.
    """

    credits: int = pydantic.Field()
    """
    Credits consumed for this language in the period.
    """

    characters: int = pydantic.Field()
    """
    Characters processed for this language in the period.
    """

    lines: int = pydantic.Field()
    """
    Script lines generated for this language in the period.
    """

    allocation_basis: str = pydantic.Field()
    """
    How credit share is allocated for this language (e.g. `characters`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
