# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_activity_bucket_out import UsageActivityBucketOut
from .usage_activity_peak_out import UsageActivityPeakOut
from .usage_activity_summary_out_bucket_unit import UsageActivitySummaryOutBucketUnit
from .usage_activity_summary_out_view import UsageActivitySummaryOutView


class UsageActivitySummaryOut(UniversalBaseModel):
    view: UsageActivitySummaryOutView
    bucket_unit: UsageActivitySummaryOutBucketUnit
    range_label: str
    buckets: typing.Optional[typing.List[UsageActivityBucketOut]] = None
    total: int = pydantic.Field()
    """
    Total generated line count across all activity buckets.
    """

    avg: float = pydantic.Field()
    """
    Average generated line count per activity bucket, rounded to 1 decimal.
    """

    peak: typing.Optional[UsageActivityPeakOut] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
