# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_activity_summary_out import UsageActivitySummaryOut
from .usage_characters_out import UsageCharactersOut
from .usage_credits_out import UsageCreditsOut
from .usage_daily_out import UsageDailyOut
from .usage_lines_out import UsageLinesOut
from .usage_period_out import UsagePeriodOut
from .usage_runs_out import UsageRunsOut
from .usage_summary_out_activity_view import UsageSummaryOutActivityView
from .usage_summary_out_range import UsageSummaryOutRange


class UsageSummaryOut(UniversalBaseModel):
    range: UsageSummaryOutRange
    activity_view: UsageSummaryOutActivityView
    timezone: str
    period: UsagePeriodOut
    credits: UsageCreditsOut
    characters: UsageCharactersOut
    lines: UsageLinesOut
    runs: UsageRunsOut
    activity: UsageActivitySummaryOut
    daily: typing.Optional[typing.List[UsageDailyOut]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
