# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_activity_action import UsageActivityAction
from .usage_activity_resource_out import UsageActivityResourceOut
from .usage_activity_user_out import UsageActivityUserOut


class UsageActivityOut(UniversalBaseModel):
    id: str
    timestamp: dt.datetime
    user: typing.Optional[UsageActivityUserOut] = None
    action: UsageActivityAction
    kind: str
    resource: UsageActivityResourceOut
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    ip: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
