# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VoiceFacetItem(UniversalBaseModel):
    """
    One selectable filter option (chip) for the voice browser filter bar.

    ``value`` is the exact token the caller passes back to ``GET /voices``
    (a provider/model key, a lowercase BCP-47 locale, or an enum value like
    ``female``). ``label`` is the display name for provider/model facets and
    ``None`` for languages and enum dimensions — the FE holds those labels (it
    renders locale flags/names from the code via ``Intl``). ``count`` is the
    number of voices matching ``value`` under the current request context
    (tab/workspace scope + every OTHER active filter — see ``VoiceFacetsOut``).

    For ``models``, ``count`` includes only voices that explicitly declare ``value``
    in ``supported_models``. For ``languages``, it includes voices that declare the
    exact regional locale plus voices that declare its bare family (for example,
    ``en`` contributes to every supported ``en-*`` locale).

    A voice with no declared ``supported_models`` is "general use" — ``GET /voices``
    matches it against every ``model`` filter, yet it is counted in no ``models``
    chip, so a ``models`` chip's ``count`` can be lower than the row count
    ``GET /voices?model=<value>`` actually returns. ``languages`` has no such gap:
    a voice with no declared locales is excluded from both the language chips AND
    ``GET /voices?language=<value>``, so language chip counts match the filtered
    row counts.
    """

    value: str
    label: typing.Optional[str] = None
    count: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
