# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .voice_accent import VoiceAccent
from .voice_age import VoiceAge
from .voice_category import VoiceCategory
from .voice_gender import VoiceGender
from .voice_source import VoiceSource


class VoiceSimilarOut(UniversalBaseModel):
    id: str
    name: str
    provider: str
    provider_voice_id: str
    description: typing.Optional[str] = None
    is_active: bool
    gender: typing.Optional[VoiceGender] = None
    accent: typing.Optional[VoiceAccent] = None
    age: typing.Optional[VoiceAge] = None
    category: typing.Optional[VoiceCategory] = None
    color: typing.Optional[str] = None
    tags: typing.Optional[typing.List[str]] = None
    descriptor: typing.Optional[str] = None
    uses_count: typing.Optional[int] = None
    user_id: typing.Optional[str] = None
    source: typing.Optional[VoiceSource] = None
    duration_seconds: typing.Optional[float] = None
    sample_url: typing.Optional[str] = None
    supported_languages: typing.Optional[typing.List[str]] = None
    supported_models: typing.Optional[typing.List[str]] = None
    is_favorite: typing.Optional[bool] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    similarity_score: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
