# This file was auto-generated by Fern from our API Definition.

import typing

VoiceAccent = typing.Union[
    typing.Literal[
        "american",
        "british",
        "australian",
        "indian",
        "canadian",
        "irish",
        "african",
        "european",
        "east_asian",
        "southeast_asian",
        "latin_american",
        "middle_eastern",
        "slavic",
        "spanish",
        "french",
        "german",
        "italian",
        "portuguese",
        "japanese",
        "korean",
        "chinese",
        "thai",
        "vietnamese",
        "other",
    ],
    typing.Any,
]
