# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VoiceModelCapabilityOut(UniversalBaseModel):
    model: str = pydantic.Field()
    """
    Model identifier for this exact voice capability.
    """

    languages_known: bool = pydantic.Field()
    """
    Whether the provider authoritatively supplied locale metadata. False means unknown; true with an empty supported_languages array means known-empty. On app-facing responses an empty array can ALSO mean the provider declared locales for this model but none of them is officially supported — the voice was kept because a sibling model carries an official locale. Use the admin API to see the raw declarations.
    """

    supported_languages: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
