# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_data_validation_out_status import WorkflowRunDataValidationOutStatus


class WorkflowRunDataValidationOut(UniversalBaseModel):
    """
    Per-validator scoring entry for a single line (POD-599).

    WER entries populate ``wer``/``cer``/``transcript``; naturalness entries
    populate ``score`` (0-100). All fields except ``kind`` and ``status`` are
    optional so future validator kinds can omit inapplicable fields.
    """

    kind: str
    label: typing.Optional[str] = None
    score: typing.Optional[float] = None
    status: WorkflowRunDataValidationOutStatus
    reason: typing.Optional[str] = None
    wer: typing.Optional[float] = None
    cer: typing.Optional[float] = None
    transcript: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
