# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_data_dropped_verdict_out import WorkflowRunDataDroppedVerdictOut


class WorkflowRunDataDroppedOut(UniversalBaseModel):
    verdicts: typing.Optional[typing.List[WorkflowRunDataDroppedVerdictOut]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
