# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkflowRunDataDroppedVerdictOut(UniversalBaseModel):
    """
    One failing validator's verdict on a dropped take.

    A take can fail several parallel validators at once; ``validator_node_id``
    disambiguates two validators of the same kind (e.g. two WER nodes with
    different thresholds). ``threshold`` is the pass bar that actually gated
    the line (schema defaults resolved); null only for invalid snapshots.
    """

    validator_node_id: str
    validator_kind: str
    validator_label: str
    score: typing.Optional[float] = None
    threshold: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
