# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_overview_node_state_out import WorkflowRunOverviewNodeStateOut


class WorkflowRunOverviewSnapshotOut(UniversalBaseModel):
    definition: typing.Dict[str, typing.Any]
    node_states: typing.Optional[typing.List[WorkflowRunOverviewNodeStateOut]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
