# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_sink_output_out import WorkflowRunSinkOutputOut


class WorkflowRunOutputsOut(UniversalBaseModel):
    run_id: str
    run_status: str
    credits: typing.Optional[int] = None
    credits_absorbed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Credits discounted by floor-rounding for this run. This is the sub-credit remainder above the charged (floored) credits; charged credits plus this value reconstructs true cost only for fully covered, uncapped runs. Returns 0 for unsettled or legacy runs.
    """

    outputs: typing.List[WorkflowRunSinkOutputOut]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
