# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowRunAnalysisCreditRowOutStatus = typing.Union[
    typing.Literal["recorded", "recorded_incomplete", "free", "missing", "not_completed"], typing.Any
]
