# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_data_card_out import WorkflowRunDataCardOut
from .workflow_run_data_row_out_auto_corrected_status import WorkflowRunDataRowOutAutoCorrectedStatus
from .workflow_run_data_row_out_script_status import WorkflowRunDataRowOutScriptStatus


class WorkflowRunDataRowOut(UniversalBaseModel):
    id: str
    line_index: typing.Optional[int] = None
    line_id: typing.Optional[str] = None
    source_line_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source line identity for unresolved translated rows. Null when the grouped source line has been merged; card-level source_line_id preserves translation provenance.
    """

    script: typing.Optional[str] = None
    script_status: WorkflowRunDataRowOutScriptStatus
    script_reason: typing.Optional[str] = None
    auto_corrected: typing.Optional[int] = None
    auto_corrected_status: typing.Optional[WorkflowRunDataRowOutAutoCorrectedStatus] = None
    auto_corrected_reason: typing.Optional[str] = None
    cards: typing.Optional[typing.List[WorkflowRunDataCardOut]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
