# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .triggered_by_out import TriggeredByOut


class WorkflowRunOut(UniversalBaseModel):
    id: str
    workflow_id: str
    status: str
    run_number: int
    total_nodes: typing.Optional[int] = None
    total_steps: typing.Optional[int] = None
    finished_steps: typing.Optional[int] = None
    token_cost: int
    usage_summary: typing.Optional[typing.Dict[str, typing.Any]] = None
    started_at: typing.Optional[dt.datetime] = None
    completed_at: typing.Optional[dt.datetime] = None
    pause_requested_at: typing.Optional[dt.datetime] = None
    paused_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    error: typing.Optional[str] = None
    has_export: typing.Optional[bool] = None
    triggered_by: typing.Optional[TriggeredByOut] = None
    credits: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
