# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkflowRunDataErrorCountsOut(UniversalBaseModel):
    """
    The three edit operations a word-accuracy (``kind == "wer"``) rate is the sum of.

    A rate alone doesn't say what went wrong. The same 0.25 can be three deletions (the
    take dropped scripted words), three insertions (words heard that the script never
    had), or three substitutions (the mispronunciation case) — three different fixes.
    Counted in the units of the metric that actually scored the take (``scored_on``):
    words for ``"wer"``, characters for ``"cer"``.

    ``reference_units`` is the denominator those counts were divided by, so
    ``(substitutions + insertions + deletions) / reference_units`` reproduces the
    entry's ``wer``/``cer`` exactly and a client can render "3 of 24 words" without
    re-deriving the reference length (which it cannot: the denominator counts the
    CANONICALIZED reference, not the displayed ``script``).

    These are NOT a summary of ``segments``: the counts come from the error-rate
    alignment, the highlight spans from a separate diff alignment, so
    ``substitutions + deletions`` may differ from the span count by a unit or two on a
    badly-mangled take, and tallying ``segments[].error_type`` will not always reproduce
    these numbers. Use the counts for the line's totals — the ones the rate is actually
    the sum of, and the only place insertions are reported at all — and the spans for
    which word failed and how.
    """

    substitutions: int
    insertions: int
    deletions: int
    reference_units: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
