# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.api_list_response_usage_activity_out import ApiListResponseUsageActivityOut
from ..types.api_response_usage_by_language_out import ApiResponseUsageByLanguageOut
from ..types.api_response_usage_summary_out import ApiResponseUsageSummaryOut
from ..types.usage_activity_action import UsageActivityAction
from .types.usage_activity_api_v1usage_activity_get_request_range import UsageActivityApiV1UsageActivityGetRequestRange
from .types.usage_by_language_api_v1usage_by_language_get_request_activity_view import (
    UsageByLanguageApiV1UsageByLanguageGetRequestActivityView,
)
from .types.usage_by_language_api_v1usage_by_language_get_request_range import (
    UsageByLanguageApiV1UsageByLanguageGetRequestRange,
)
from .types.usage_summary_api_v1usage_summary_get_request_activity_view import (
    UsageSummaryApiV1UsageSummaryGetRequestActivityView,
)
from .types.usage_summary_api_v1usage_summary_get_request_range import UsageSummaryApiV1UsageSummaryGetRequestRange
from pydantic import ValidationError


class RawUsageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def usage_summary(
        self,
        *,
        range: typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestRange] = None,
        activity_view: typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestActivityView] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseUsageSummaryOut]:
        """
        Return workspace usage totals plus tab-specific aggregate activity buckets.

        Parameters
        ----------
        range : typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestRange]
            Rolling local calendar-day range.

        activity_view : typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestActivityView]
            Activity chart view: daily=7 local days, weekly=12 Monday-start weeks, monthly=12 months.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseUsageSummaryOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/usage/summary",
            method="GET",
            params={
                "range": range,
                "activity_view": activity_view,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseUsageSummaryOut,
                    parse_obj_as(
                        type_=ApiResponseUsageSummaryOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def usage_by_language(
        self,
        *,
        range: typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestRange] = None,
        activity_view: typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestActivityView] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseUsageByLanguageOut]:
        """
        Return workspace generated-audio usage grouped by language.

        ``share`` is a 0..1 fraction. When ``activity_view`` is supplied, rows use
        that tab's local-calendar period; otherwise they preserve legacy ``range``
        behavior.

        Parameters
        ----------
        range : typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestRange]
            Rolling local calendar-day range.

        activity_view : typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestActivityView]
            Optional activity view period to align language rows with the selected Usage tab. When supplied, range is ignored and range in the response is null.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseUsageByLanguageOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/usage/by-language",
            method="GET",
            params={
                "range": range,
                "activity_view": activity_view,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseUsageByLanguageOut,
                    parse_obj_as(
                        type_=ApiResponseUsageByLanguageOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def usage_activity(
        self,
        *,
        range: typing.Optional[UsageActivityApiV1UsageActivityGetRequestRange] = None,
        type: typing.Optional[UsageActivityAction] = None,
        user_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiListResponseUsageActivityOut]:
        """
        Return the workspace usage activity feed with stable action filters and cursor pagination.

        Parameters
        ----------
        range : typing.Optional[UsageActivityApiV1UsageActivityGetRequestRange]
            Rolling local calendar-day range.

        type : typing.Optional[UsageActivityAction]
            Filter by usage activity type.

        user_id : typing.Optional[str]
            Filter by actor user id.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque pagination cursor.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiListResponseUsageActivityOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/usage/activity",
            method="GET",
            params={
                "range": range,
                "type": type,
                "user_id": user_id,
                "limit": limit,
                "cursor": cursor,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseUsageActivityOut,
                    parse_obj_as(
                        type_=ApiListResponseUsageActivityOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawUsageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def usage_summary(
        self,
        *,
        range: typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestRange] = None,
        activity_view: typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestActivityView] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseUsageSummaryOut]:
        """
        Return workspace usage totals plus tab-specific aggregate activity buckets.

        Parameters
        ----------
        range : typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestRange]
            Rolling local calendar-day range.

        activity_view : typing.Optional[UsageSummaryApiV1UsageSummaryGetRequestActivityView]
            Activity chart view: daily=7 local days, weekly=12 Monday-start weeks, monthly=12 months.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseUsageSummaryOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/usage/summary",
            method="GET",
            params={
                "range": range,
                "activity_view": activity_view,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseUsageSummaryOut,
                    parse_obj_as(
                        type_=ApiResponseUsageSummaryOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def usage_by_language(
        self,
        *,
        range: typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestRange] = None,
        activity_view: typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestActivityView] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseUsageByLanguageOut]:
        """
        Return workspace generated-audio usage grouped by language.

        ``share`` is a 0..1 fraction. When ``activity_view`` is supplied, rows use
        that tab's local-calendar period; otherwise they preserve legacy ``range``
        behavior.

        Parameters
        ----------
        range : typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestRange]
            Rolling local calendar-day range.

        activity_view : typing.Optional[UsageByLanguageApiV1UsageByLanguageGetRequestActivityView]
            Optional activity view period to align language rows with the selected Usage tab. When supplied, range is ignored and range in the response is null.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseUsageByLanguageOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/usage/by-language",
            method="GET",
            params={
                "range": range,
                "activity_view": activity_view,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseUsageByLanguageOut,
                    parse_obj_as(
                        type_=ApiResponseUsageByLanguageOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def usage_activity(
        self,
        *,
        range: typing.Optional[UsageActivityApiV1UsageActivityGetRequestRange] = None,
        type: typing.Optional[UsageActivityAction] = None,
        user_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        timezone: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiListResponseUsageActivityOut]:
        """
        Return the workspace usage activity feed with stable action filters and cursor pagination.

        Parameters
        ----------
        range : typing.Optional[UsageActivityApiV1UsageActivityGetRequestRange]
            Rolling local calendar-day range.

        type : typing.Optional[UsageActivityAction]
            Filter by usage activity type.

        user_id : typing.Optional[str]
            Filter by actor user id.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque pagination cursor.

        timezone : typing.Optional[str]
            IANA timezone for local day bucketing.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiListResponseUsageActivityOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/usage/activity",
            method="GET",
            params={
                "range": range,
                "type": type,
                "user_id": user_id,
                "limit": limit,
                "cursor": cursor,
                "timezone": timezone,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseUsageActivityOut,
                    parse_obj_as(
                        type_=ApiListResponseUsageActivityOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
