# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_response_dict import ApiResponseDict
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def clerk_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseDict:
        """
        Handle Clerk webhook events. Verifies svix signature.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.webhooks.clerk_webhook()
        """
        _response = self._raw_client.clerk_webhook(request_options=request_options)
        return _response.data

    def stripe_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseDict:
        """
        Handle Stripe webhook events. Verifies Stripe-Signature header.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.webhooks.stripe_webhook()
        """
        _response = self._raw_client.stripe_webhook(request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def clerk_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseDict:
        """
        Handle Clerk webhook events. Verifies svix signature.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.clerk_webhook()


        asyncio.run(main())
        """
        _response = await self._raw_client.clerk_webhook(request_options=request_options)
        return _response.data

    async def stripe_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiResponseDict:
        """
        Handle Stripe webhook events. Verifies Stripe-Signature header.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.stripe_webhook()


        asyncio.run(main())
        """
        _response = await self._raw_client.stripe_webhook(request_options=request_options)
        return _response.data
