# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.api_counted_list_response_catalog_voice_out import ApiCountedListResponseCatalogVoiceOut
from ..types.api_list_response_catalog_model_out import ApiListResponseCatalogModelOut
from ..types.api_list_response_catalog_provider_out import ApiListResponseCatalogProviderOut
from ..types.api_response_catalog_model_out import ApiResponseCatalogModelOut
from ..types.api_response_catalog_provider_out import ApiResponseCatalogProviderOut
from ..types.http_validation_error import HttpValidationError
from pydantic import ValidationError


class RawProvidersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_catalog_providers(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ApiListResponseCatalogProviderOut]:
        """
        List TTS providers in the public catalog.

        Returns the processing (TTS) provider catalog with a per-provider model count
        and a HATEOAS link to each provider's models. Lean / customer-safe — cost,
        credentials, and base URLs are never exposed. Requires `X-Workspace-Id` (or a
        workspace-bound API key with the `catalog:read` scope), matching `/voices`.

        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiListResponseCatalogProviderOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/providers",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseCatalogProviderOut,
                    parse_obj_as(
                        type_=ApiListResponseCatalogProviderOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_catalog_provider(
        self,
        provider: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseCatalogProviderOut]:
        """
        Get a single TTS provider by canonical name (e.g. `cartesia`).

        Parameters
        ----------
        provider : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseCatalogProviderOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseCatalogProviderOut,
                    parse_obj_as(
                        type_=ApiResponseCatalogProviderOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_catalog_provider_models(
        self,
        provider: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiListResponseCatalogModelOut]:
        """
        List a provider's TTS models, each with its `config_schema` and live `voice_count`.

        Parameters
        ----------
        provider : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiListResponseCatalogModelOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseCatalogModelOut,
                    parse_obj_as(
                        type_=ApiListResponseCatalogModelOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_catalog_provider_model_voices(
        self,
        provider: str,
        model: str,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiCountedListResponseCatalogVoiceOut]:
        """
        List platform voices catalogued under an exact `(provider, model)`.

        Lean voice shape with a presigned `preview_url`. Platform catalog voices only
        (System workspace); model-less voices are excluded. Paginated via `offset` /
        `limit`. The flat `/voices?provider=&model=` endpoint remains for the picker.

        Parameters
        ----------
        provider : str

        model : str

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiCountedListResponseCatalogVoiceOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models/{encode_path_param(model)}/voices",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiCountedListResponseCatalogVoiceOut,
                    parse_obj_as(
                        type_=ApiCountedListResponseCatalogVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_catalog_provider_model(
        self,
        provider: str,
        model: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ApiResponseCatalogModelOut]:
        """
        Get a single TTS model — `config_schema` + live `voice_count`.

        Parameters
        ----------
        provider : str

        model : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ApiResponseCatalogModelOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models/{encode_path_param(model)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseCatalogModelOut,
                    parse_obj_as(
                        type_=ApiResponseCatalogModelOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawProvidersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_catalog_providers(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ApiListResponseCatalogProviderOut]:
        """
        List TTS providers in the public catalog.

        Returns the processing (TTS) provider catalog with a per-provider model count
        and a HATEOAS link to each provider's models. Lean / customer-safe — cost,
        credentials, and base URLs are never exposed. Requires `X-Workspace-Id` (or a
        workspace-bound API key with the `catalog:read` scope), matching `/voices`.

        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiListResponseCatalogProviderOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/providers",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseCatalogProviderOut,
                    parse_obj_as(
                        type_=ApiListResponseCatalogProviderOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_catalog_provider(
        self,
        provider: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseCatalogProviderOut]:
        """
        Get a single TTS provider by canonical name (e.g. `cartesia`).

        Parameters
        ----------
        provider : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseCatalogProviderOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseCatalogProviderOut,
                    parse_obj_as(
                        type_=ApiResponseCatalogProviderOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_catalog_provider_models(
        self,
        provider: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiListResponseCatalogModelOut]:
        """
        List a provider's TTS models, each with its `config_schema` and live `voice_count`.

        Parameters
        ----------
        provider : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiListResponseCatalogModelOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiListResponseCatalogModelOut,
                    parse_obj_as(
                        type_=ApiListResponseCatalogModelOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_catalog_provider_model_voices(
        self,
        provider: str,
        model: str,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiCountedListResponseCatalogVoiceOut]:
        """
        List platform voices catalogued under an exact `(provider, model)`.

        Lean voice shape with a presigned `preview_url`. Platform catalog voices only
        (System workspace); model-less voices are excluded. Paginated via `offset` /
        `limit`. The flat `/voices?provider=&model=` endpoint remains for the picker.

        Parameters
        ----------
        provider : str

        model : str

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiCountedListResponseCatalogVoiceOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models/{encode_path_param(model)}/voices",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
            },
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiCountedListResponseCatalogVoiceOut,
                    parse_obj_as(
                        type_=ApiCountedListResponseCatalogVoiceOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_catalog_provider_model(
        self,
        provider: str,
        model: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ApiResponseCatalogModelOut]:
        """
        Get a single TTS model — `config_schema` + live `voice_count`.

        Parameters
        ----------
        provider : str

        model : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ApiResponseCatalogModelOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/providers/{encode_path_param(provider)}/models/{encode_path_param(model)}",
            method="GET",
            headers={
                "X-Workspace-Id": str(workspace_id) if workspace_id is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ApiResponseCatalogModelOut,
                    parse_obj_as(
                        type_=ApiResponseCatalogModelOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
