# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_list_response_workspace_out import ApiListResponseWorkspaceOut
from ..types.api_response_dict import ApiResponseDict
from ..types.api_response_slug_availability_out import ApiResponseSlugAvailabilityOut
from ..types.api_response_workspace_out import ApiResponseWorkspaceOut
from .raw_client import AsyncRawWorkspacesClient, RawWorkspacesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkspacesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkspacesClient
        """
        return self._raw_client

    def list_workspaces(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseWorkspaceOut:
        """
        List all workspaces the current user is a member of.

        Returns workspaces where the caller has any role (admin, editor, or
        viewer), including workspaces they own and workspaces they joined via
        invite. Results are paginated; omits soft-deleted workspaces and the
        internal system workspace.

        Parameters
        ----------
        offset : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseWorkspaceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.list_workspaces()
        """
        _response = self._raw_client.list_workspaces(offset=offset, limit=limit, request_options=request_options)
        return _response.data

    def create_workspace(
        self,
        *,
        name: str,
        slug: typing.Optional[str] = OMIT,
        color_idx: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseWorkspaceOut:
        """
        Create a new workspace owned by the current user.

        Workspaces are the top-level container for all resources (workflows,
        voices, dictionary entries, members). Every resource is scoped to exactly
        one workspace via the `X-Workspace-Id` header on subsequent requests.

        The authenticated user becomes the workspace owner and is automatically
        added as an `admin` member. An optional `slug` (1–50 characters,
        lowercase kebab-case) can be supplied for a human-readable workspace
        identifier; if omitted, one is auto-generated from `name`. Returns 409
        if the slug is already taken, 422 if the slug format is invalid or uses
        a reserved word.

        The number of workspaces a user may own is plan-gated. Attempting to
        exceed the limit returns 402.

        Parameters
        ----------
        name : str
            Human-readable workspace name (1–200 characters, non-blank).

        slug : typing.Optional[str]
            Optional URL-safe identifier (lowercase kebab-case, 1–50 characters). Auto-generated from `name` if omitted. Returns 409 if taken, 422 if invalid or reserved.

        color_idx : typing.Optional[int]
            Index into the workspace color palette (0–6).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.create_workspace(
            name="name",
        )
        """
        _response = self._raw_client.create_workspace(
            name=name, slug=slug, color_idx=color_idx, request_options=request_options
        )
        return _response.data

    def slug_available(
        self,
        *,
        slug: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseSlugAvailabilityOut:
        """
        Check whether a slug is available for the current workspace. Admin only.

        Returns `{ available: true }` if the slug is valid, not reserved, and
        not already claimed by another workspace. When unavailable, `reason`
        indicates why: `invalid` (format/length), `reserved` (blocked word), or
        `taken` (already in use globally). The workspace's own current slug is
        self-excluded, so an admin can safely check their existing slug without
        receiving `taken`.

        This is an advisory point-in-time check — a concurrent `POST /workspaces`
        or `PATCH /workspaces/{id}` from another session can claim the slug
        between this response and the caller's write. Always handle 409
        `WORKSPACE_SLUG_TAKEN` on `create_workspace` and `update_workspace`.

        Requires the `X-Workspace-Id` header (the workspace being renamed) and
        admin role in that workspace. Missing/invalid header returns 400; not a
        member returns 404; not admin returns 403.

        Parameters
        ----------
        slug : str
            Candidate slug; normalized (strip().lower()) before checks.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseSlugAvailabilityOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.slug_available(
            slug="slug",
        )
        """
        _response = self._raw_client.slug_available(
            slug=slug, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def get_workspace(
        self, workspace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseWorkspaceOut:
        """
        Fetch a single workspace by ID.

        Returns the workspace if the current user is an active member (any role).
        Returns 404 if the workspace does not exist, has been deleted, or the
        caller is not a member — the two cases are intentionally indistinguishable
        to prevent workspace enumeration.

        Parameters
        ----------
        workspace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.get_workspace(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.get_workspace(workspace_id, request_options=request_options)
        return _response.data

    def delete_workspace(
        self, workspace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseDict:
        """
        Delete a workspace and all of its resources. Owner only.

        Soft-deletes the workspace and cascades to all owned resources (workflows,
        voices, dictionary entries, members, etc.). The workspace and its contents
        become inaccessible via the API immediately. Data is retained for the GDPR
        retention period before permanent purge.

        Only the workspace owner (the user who created it) can delete it; admin
        members who are not the owner receive 404. Returns 404 if the workspace
        does not exist or the caller is not the owner.

        Parameters
        ----------
        workspace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.delete_workspace(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.delete_workspace(workspace_id, request_options=request_options)
        return _response.data

    def update_workspace(
        self,
        workspace_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        color_idx: typing.Optional[int] = OMIT,
        routing_price_sensitivity: typing.Optional[float] = OMIT,
        routing_llm_fit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseWorkspaceOut:
        """
        Update a workspace's name, color palette index, and/or slug. Admin only.

        All fields are optional — supply only the fields you want to change.
        `slug` follows the same validation rules as on create (lowercase
        kebab-case, 1–50 characters, no reserved words). Returns 409 if the new
        slug is already claimed by another workspace, 422 if the slug format is
        invalid or reserved. Re-setting the workspace's current slug to itself
        never returns 409.

        Only workspace admins may call this endpoint; other members receive 404
        (same as not-found, to avoid leaking membership details to non-members).

        Parameters
        ----------
        workspace_id : str

        name : typing.Optional[str]
            New workspace name. Omit to leave unchanged.

        slug : typing.Optional[str]
            New slug (lowercase kebab-case, 1–50 characters). Omit to leave unchanged. Returns 409 if taken, 422 if invalid or reserved.

        color_idx : typing.Optional[int]
            New color palette index (0–6). Omit to leave unchanged.

        routing_price_sensitivity : typing.Optional[float]
            New voice-selection price/quality balance (0.0 = pure quality, 1.0 = pure price, 0.5 = balanced). Omit to leave unchanged.

        routing_llm_fit : typing.Optional[bool]
            New setting for whether automatic voice selection also weighs content fit. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        from onepin import OnePinClient

        client = OnePinClient(
            token="YOUR_TOKEN",
        )
        client.workspaces.update_workspace(
            workspace_id="workspace_id",
        )
        """
        _response = self._raw_client.update_workspace(
            workspace_id,
            name=name,
            slug=slug,
            color_idx=color_idx,
            routing_price_sensitivity=routing_price_sensitivity,
            routing_llm_fit=routing_llm_fit,
            request_options=request_options,
        )
        return _response.data


class AsyncWorkspacesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkspacesClient
        """
        return self._raw_client

    async def list_workspaces(
        self,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiListResponseWorkspaceOut:
        """
        List all workspaces the current user is a member of.

        Returns workspaces where the caller has any role (admin, editor, or
        viewer), including workspaces they own and workspaces they joined via
        invite. Results are paginated; omits soft-deleted workspaces and the
        internal system workspace.

        Parameters
        ----------
        offset : typing.Optional[int]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiListResponseWorkspaceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.list_workspaces()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_workspaces(offset=offset, limit=limit, request_options=request_options)
        return _response.data

    async def create_workspace(
        self,
        *,
        name: str,
        slug: typing.Optional[str] = OMIT,
        color_idx: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseWorkspaceOut:
        """
        Create a new workspace owned by the current user.

        Workspaces are the top-level container for all resources (workflows,
        voices, dictionary entries, members). Every resource is scoped to exactly
        one workspace via the `X-Workspace-Id` header on subsequent requests.

        The authenticated user becomes the workspace owner and is automatically
        added as an `admin` member. An optional `slug` (1–50 characters,
        lowercase kebab-case) can be supplied for a human-readable workspace
        identifier; if omitted, one is auto-generated from `name`. Returns 409
        if the slug is already taken, 422 if the slug format is invalid or uses
        a reserved word.

        The number of workspaces a user may own is plan-gated. Attempting to
        exceed the limit returns 402.

        Parameters
        ----------
        name : str
            Human-readable workspace name (1–200 characters, non-blank).

        slug : typing.Optional[str]
            Optional URL-safe identifier (lowercase kebab-case, 1–50 characters). Auto-generated from `name` if omitted. Returns 409 if taken, 422 if invalid or reserved.

        color_idx : typing.Optional[int]
            Index into the workspace color palette (0–6).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.create_workspace(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_workspace(
            name=name, slug=slug, color_idx=color_idx, request_options=request_options
        )
        return _response.data

    async def slug_available(
        self,
        *,
        slug: str,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseSlugAvailabilityOut:
        """
        Check whether a slug is available for the current workspace. Admin only.

        Returns `{ available: true }` if the slug is valid, not reserved, and
        not already claimed by another workspace. When unavailable, `reason`
        indicates why: `invalid` (format/length), `reserved` (blocked word), or
        `taken` (already in use globally). The workspace's own current slug is
        self-excluded, so an admin can safely check their existing slug without
        receiving `taken`.

        This is an advisory point-in-time check — a concurrent `POST /workspaces`
        or `PATCH /workspaces/{id}` from another session can claim the slug
        between this response and the caller's write. Always handle 409
        `WORKSPACE_SLUG_TAKEN` on `create_workspace` and `update_workspace`.

        Requires the `X-Workspace-Id` header (the workspace being renamed) and
        admin role in that workspace. Missing/invalid header returns 400; not a
        member returns 404; not admin returns 403.

        Parameters
        ----------
        slug : str
            Candidate slug; normalized (strip().lower()) before checks.

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseSlugAvailabilityOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.slug_available(
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.slug_available(
            slug=slug, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def get_workspace(
        self, workspace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseWorkspaceOut:
        """
        Fetch a single workspace by ID.

        Returns the workspace if the current user is an active member (any role).
        Returns 404 if the workspace does not exist, has been deleted, or the
        caller is not a member — the two cases are intentionally indistinguishable
        to prevent workspace enumeration.

        Parameters
        ----------
        workspace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.get_workspace(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_workspace(workspace_id, request_options=request_options)
        return _response.data

    async def delete_workspace(
        self, workspace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiResponseDict:
        """
        Delete a workspace and all of its resources. Owner only.

        Soft-deletes the workspace and cascades to all owned resources (workflows,
        voices, dictionary entries, members, etc.). The workspace and its contents
        become inaccessible via the API immediately. Data is retained for the GDPR
        retention period before permanent purge.

        Only the workspace owner (the user who created it) can delete it; admin
        members who are not the owner receive 404. Returns 404 if the workspace
        does not exist or the caller is not the owner.

        Parameters
        ----------
        workspace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseDict
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.delete_workspace(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_workspace(workspace_id, request_options=request_options)
        return _response.data

    async def update_workspace(
        self,
        workspace_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        color_idx: typing.Optional[int] = OMIT,
        routing_price_sensitivity: typing.Optional[float] = OMIT,
        routing_llm_fit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiResponseWorkspaceOut:
        """
        Update a workspace's name, color palette index, and/or slug. Admin only.

        All fields are optional — supply only the fields you want to change.
        `slug` follows the same validation rules as on create (lowercase
        kebab-case, 1–50 characters, no reserved words). Returns 409 if the new
        slug is already claimed by another workspace, 422 if the slug format is
        invalid or reserved. Re-setting the workspace's current slug to itself
        never returns 409.

        Only workspace admins may call this endpoint; other members receive 404
        (same as not-found, to avoid leaking membership details to non-members).

        Parameters
        ----------
        workspace_id : str

        name : typing.Optional[str]
            New workspace name. Omit to leave unchanged.

        slug : typing.Optional[str]
            New slug (lowercase kebab-case, 1–50 characters). Omit to leave unchanged. Returns 409 if taken, 422 if invalid or reserved.

        color_idx : typing.Optional[int]
            New color palette index (0–6). Omit to leave unchanged.

        routing_price_sensitivity : typing.Optional[float]
            New voice-selection price/quality balance (0.0 = pure quality, 1.0 = pure price, 0.5 = balanced). Omit to leave unchanged.

        routing_llm_fit : typing.Optional[bool]
            New setting for whether automatic voice selection also weighs content fit. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiResponseWorkspaceOut
            Successful Response

        Examples
        --------
        import asyncio

        from onepin import AsyncOnePinClient

        client = AsyncOnePinClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.update_workspace(
                workspace_id="workspace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_workspace(
            workspace_id,
            name=name,
            slug=slug,
            color_idx=color_idx,
            routing_price_sensitivity=routing_price_sensitivity,
            routing_llm_fit=routing_llm_fit,
            request_options=request_options,
        )
        return _response.data
