# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_dictionary_entries_api_v1dictionary_get_request_language import (
        ListDictionaryEntriesApiV1DictionaryGetRequestLanguage,
    )
    from .list_dictionary_entries_api_v1dictionary_get_request_order import (
        ListDictionaryEntriesApiV1DictionaryGetRequestOrder,
    )
    from .list_dictionary_entries_api_v1dictionary_get_request_sort import (
        ListDictionaryEntriesApiV1DictionaryGetRequestSort,
    )
    from .search_dictionary_entries_api_v1dictionary_search_get_request_language_item import (
        SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem,
    )
    from .search_dictionary_entries_api_v1dictionary_search_get_request_order import (
        SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder,
    )
    from .search_dictionary_entries_api_v1dictionary_search_get_request_sort import (
        SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ListDictionaryEntriesApiV1DictionaryGetRequestLanguage": ".list_dictionary_entries_api_v1dictionary_get_request_language",
    "ListDictionaryEntriesApiV1DictionaryGetRequestOrder": ".list_dictionary_entries_api_v1dictionary_get_request_order",
    "ListDictionaryEntriesApiV1DictionaryGetRequestSort": ".list_dictionary_entries_api_v1dictionary_get_request_sort",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem": ".search_dictionary_entries_api_v1dictionary_search_get_request_language_item",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder": ".search_dictionary_entries_api_v1dictionary_search_get_request_order",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort": ".search_dictionary_entries_api_v1dictionary_search_get_request_sort",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListDictionaryEntriesApiV1DictionaryGetRequestLanguage",
    "ListDictionaryEntriesApiV1DictionaryGetRequestOrder",
    "ListDictionaryEntriesApiV1DictionaryGetRequestSort",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestLanguageItem",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestOrder",
    "SearchDictionaryEntriesApiV1DictionarySearchGetRequestSort",
]
