# This file was auto-generated by Fern from our API Definition.

import typing

ListVoicesRequestProviderItem = typing.Union[
    typing.Literal["cartesia", "elevenlabs", "naver", "respeecher", "rime"], typing.Any
]
