# This file was auto-generated by Fern from our API Definition.

import typing

ListVoicesRequestSourceItem = typing.Union[typing.Literal["platform", "recorded", "uploaded", "workspace"], typing.Any]
